project:
  type: website
  output-dir: docs

website:
  title: "Responsible Datasets in Context"
  navbar:
    right:
      - datasets.qmd
      - about.qmd
      - icon: github
        href: https://github.com/melaniewalsh/responsible-datasets-in-context

format:
  html:
    theme: lux
    css: styles.css



