{
  "hash": "083d9aff76a3c1b1612fa2ad18b9af62",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Top 500 \"Greatest\" Novels (1021-2015)\nauthor: Anna Preus and Aashna Sheth\nformat:\n  html: default\n  pdf: default\nlisting:\n  id: exercise-posts\n  contents: exercises\n  exclude:\n    categories: dataset\n  sort: date desc\n  type: table\n  fields:\n    - date\n    - title\n    - categories\n  categories: false\n  sort-ui: false\n  filter-ui: true\n  image-height: 200px\ndate: '2024-04-10'\ncategories:\n  - libraries\n  - literature\n  - readers\n  - gender\n  - metadata\n  - full-text\n  - public domain\nimage: images/library-top-500-screenshot.png\ntoc: true\ntoc-depth: 5\nsidebar:\n  contents: auto\nformat-links:\n  - pdf\n  - docx\ncode-fold: true\neditor: visual\ndf-print: kable\ncode-tools: true\nbibliography: references/references.bib\n---\n\n::: {.panel-tabset .nav-pills}\n# Data Essay {#data-essay}\n\n## Introduction\n\nThis dataset contains information on the top 500 novels most widely held in libraries, according to [OCLC](https://www.oclc.org/en/about.html?cmpid=md_ab), a global library organization with over 16,000 member libraries in over 100 countries. The dataset includes information on authors’ biographies, library holdings, and online engagement for each novel, as well as the full text for all works that are not currently under copyright (190 novels).\n\n::: {.callout-tip icon=false}\n## Brief Survey\nIf you use our materials in your class or another setting, we would love to [hear about it](https://forms.gle/yJpQscUH9k9Rn4Qy9)!\n:::\n\n<br>\n\n\n\n```{ojs .content-visible when-format=\"html\" unless-format=\"pdf\"}\n\n//| echo: false\n\n/*Inputs.table(search, data)*/\n\nInputs.table(search, {\n  layout: \"fixed\",\n  rows: 50,\n  sort: \"top_500_rank\",\n  reverse: false,\n  format: {\n    /*RecreationVisits: x => d3.format('.2s')(x),*/\n    pub_year: x => d3.timeFormat(x),\n    author_birth: x => d3.timeFormat(x),\n    author_death: x => d3.timeFormat(x),\n    gr_num_ratings_rank: x => html`<div style='background:${color(x)}'>${d3.format('.2s')(x)}</div>`\n  }\n})\n```\n\n\n\n<br>\n\n\n\n```{ojs}\n//| echo: false\nformatted_library_data = library_data.map(d => {\n  return Object.fromEntries(\n    Object.entries(d).map(([key, value]) => [\n      key,\n      key === \"pub_year\" || key === \"author_birth\" || key === \"author_death\" ? new Date(value, 0, 1) : value\n    ])\n  );\n});\n\n```\n\n```{ojs}\n//| echo: false\nimport {SummaryTable} from \"05930c2f8350fb92\"\nviewof summary_data = SummaryTable(formatted_library_data, {\n  label: \"Top 500 Novels Summary\"\n});\n```\n\n\n\n::: {.callout-tip icon=false}\n## Creative Commons License\n<p xmlns:cc=\"http://creativecommons.org/ns#\" >This work is licensed under <a href=\"https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1\" target=\"_blank\" rel=\"license noopener noreferrer\" style=\"display:inline-block;\">CC BY 4.0<img style=\"height:22px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1\" alt=\"\"><img style=\"height:22px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1\" alt=\"\"></a></p>\n:::\n\n\n\n{{< downloadthis ../../../datasets/top-500-novels/library_top_500.csv dname = library_top_500 label = \"Download Data\" id=downloadbutton >}}\n\n\n\n\n\nThis dataset is based on a list of the [Top 500 Novels](https://www.oclc.org/en/worldcat/library100/top500.html) compiled by OCLC from information in their online database [WorldCat](https://search.worldcat.org/), the largest database of library records. The first section of the list was published online with great fanfare as the [Library Top 100](https://www.oclc.org/en/worldcat/library100.html) in 2019, accompanied by the claim that for novels, “literary greatness can be measured by how many libraries have a copy on their shelves.” \n\nWe wondered about the implications of this claim and more broadly about what it means to base ideas of “literary greatness” on the number of libraries that hold a particular work. How do historical biases in systems of literary production, preservation, and circulation figure into these kinds of claims? And how do we even define what counts as a novel? \n\nTo contextualize the initial list and dig into its claims about literary greatness, we collected information on each novel from a number of other databases, including [Wikipedia](https://www.wikipedia.org/), [Goodreads](https://www.goodreads.com/), [Project Gutenberg](https://www.gutenberg.org/), the [Virtual International Authority File (VIAF)](https://viaf.org/), and [Classify](https://www.oclc.org/go/en/classify-discontinuation.html) (a now-shuttered OCLC tool), which we have compiled here.\n\nThe dataset was created by Anna Preus and Aashna Sheth, who are also the authors of this data essay.     \n\n\n## **HISTORY**\n\nTo start, what is a novel? Today, novels are so prevalent that the term is often applied to a much wider range of books than it actually describes. “Novel” is an umbrella term for works of longform fiction in a range of genres: romance, sci-fi, historical fiction, horror, detective fiction, westerns, etc. The term generally does not apply–although these distinctions can sometimes be fuzzy–to short fiction, poetry, plays, biographies, or other non-fiction forms. The word “novel” was first used to describe a “long fictional prose narrative” in the 1600s, and the form increased in popularity across the eighteenth and nineteenth centuries. Interestingly, OCLC’s list of top 500 novels extends much further back than this. The oldest work on the list is *The Tale of Genji*, a classic work of Japanese literature written over 1,000 years ago.\n\nA key issue in literary studies is which books from the past we continue to read in the present, and which books from the present we will continue to read in the future. The vast majority of novels fall out of circulation shortly after they are published, quickly becoming part of what Margaret Cohen has called “the great unread.” When teachers assign texts in their classes and when literary scholars conduct research, they’re making choices about which texts continue to be valuable and important for people to read and study. \n\nThe term “canon” in literary studies refers to texts that continue to be considered important over time. Ankhi Mukherjee defines the canon as “a set of texts whose value and readability have borne the test of time” noting that this “ involves not merely a work’s admission into an elite club, but its induction into ongoing critical dialogue and contestations of literary value.” Canonical works continue to be read, taught, and discussed, and in popular terminology they’re often considered “classics.” These are works you might read in a high school English class: F. Scott Fitzgerald’s *The Great Gatsby*, for example, or Harper Lee’s *To Kill a Mockingbird*. \n\nOne of the things that defines a classic is the fact that it stays in print for a long period of time. When a book is published, it is issued in an edition with a specific number of physical copies. If the book is profitable, it may be re-issued in different editions over many years, and edited repeatedly by different scholars across time. If it becomes a classic, it is likely to be issued in dozens or hundreds of editions even long after the author’s death. \n\nIn addition to classics, libraries are invested in making popular new novels available to readers. The Top 500 list includes many recently published best-sellers, including books in the *Harry Potter*, *Twilight*, and *Hunger Games* series. Some highly popular books go on to become classics–Charles Dickens’s *Great Expectations*, which was wildly successful in its day, is a good example. Many popular texts, though, do not become canonical. \n\nBy focusing on the books that librarians around the world have chosen to continue to make available to readers, OCLC was able to create a list of widely read novels that includes both classic works and more recent, popular works that may not have received the same levels of literary acclaim. We wondered, though, how did OCLC’s data compare to other potential indicators of popularity or canonicity? And, for that matter, how was the list actually constructed?\n\n## **WHERE DID THE DATA COME FROM? WHO COLLECTED IT?**\n\nThe initial list of Top 500 novels was collected by a team at OCLC, the non-profit organization that manages WorldCat. It was compiled based on analysis of data in WorldCat, which consists of catalog records created by librarians around the world, and entered into WorldCat.\n\nBuilding on this list, we compiled data from a number of other databases, including Project Gutenberg, VIAF, and Wikipedia–a process that is described in greater detail below. \n\n\n##  **WHY WAS THE DATA COLLECTED? HOW IS THE DATA USED?**\n\nOCLC’s goal in producing the Top 500 list seems to be to encourage library patronage and reading. The website for the list includes a “Librarians Kit” with a variety of publicity materials–from printable bookmarks to Instagram tiles-that can help bring attention to books in the Top 500 list within libraries’ collections. \n\n\n![](images/top_500_kit.png \"image_tooltip\")\n\n\nOur goal was to collect additional data to understand better how the list was constructed, and to contextualize and nuance its claims about literary greatness.\n\n\n## **WHAT’S IN THE DATA? WHAT MAKES A BOOK A “TOP NOVEL”?**\n\nThe Top 500 list represents a massive data extraction and analysis effort on the part of OCLC. While they do not provide detailed information on how the list was compiled, they do offer a brief explanation of the process that went into creating the list on their [FAQ page](https://www.oclc.org/en/worldcat/library100/faq.html) (written in the context of the top 100, but also applies to the top 500):\n\n\n   > Materials in libraries are described and tracked in WorldCat in two ways. Any specific work of literature, music, art, history, etc., has an associated **catalog record**. This describes the item in a general sense. Every copy of the same book, for example, shares the same record. WorldCat also tracks library **holdings**, which indicate that a specific library has (or holds) at least one copy of that item.\n\n\n  > The Library 100 is based on the total number of holdings for a specific novel across all libraries that have registered that information in WorldCat. When a library tells OCLC, “We have a copy of that book available,” that counts as a holding, and in the case of The Library 100, counts as +1 toward its ranking on the list.\n\nThis process initially sounds straightforward: to create the Top 500 list, the OCLC team presumably searched the title of a work, counted the number of libraries that held each title, and published the first 500. But it turns out it’s actually much more complicated than that. In WorldCat, records are stored by edition, meaning that each edition of a particular title has its own catalog record. An individual title like, say, Miguel de Cervantes’s *Don Quixote*, may have been released in hundreds or thousands of editions since its initial publication. \n\nThis means that when developing the list, the OCLC team actually had to find all the editions of a specific title and sum the number of libraries that hold that edition across all editions. **Thus the top 500 list is not only a representation of how many libraries carry the work, but a representation of how many times a book has been re-edited and re-issued; the more editions a book has, the more records are created and the more copies of a book a library may hold.** Often, there are duplicate records for individual editions, which may affect the overall count of copies tallied by the OCLC. And when a work is translated into different languages, all the editions of all the translations are also recorded in WorldCat, which also figures into the count of total holdings for each novel. \n\n\n##  **HOW WAS THE DATA COLLECTED? WHAT ADDITIONAL DATA WAS ADDED?**\n\nWe wanted to contextualize the Library Top 500 list by compiling additional information on each novel from a range of other sources. We focused on gathering three main categories of information: information that could help us understand what types of works–and whose works–were included on the list, data that could potentially provide alternate measures of popularity or canonicity, and the full text of each novel that was in the public domain. We collected information from the following sources:\n\n**WorldCat**: we used the now-shuttered OCLC tool Classify to gather data from WorldCat on the top 100 most widely held editions of each of the 500 novels on the list. We recorded total library holdings for these top 100 editions. We consider number of editions as a potential alternate measure of canonicity, although it is necessarily affected by the amount of time that has passed since the initial publication of the novel.  \n\n**VIAF: **The Virtual International Authority File is an OCLC-run database that contains structured records–called “name authority files”–for individual authors and creators. We used VIAF to gather information on authors whose novels were included on the list, including their birth and death dates, nationalities, genders, and occupations.\n\n![Examplf of author VIAF](images/viaf_example.png \"image_tooltip\")\n\n**Wikipedia: **we used Wikipedia, the popular, free, volunteer-authored encyclopedia, to identify the year of first publication for each novel on the list.\n\n**Goodreads: **Goodreads, which is owned by Amazon, is the largest social networking site related to books, with over 150 million members. Itt allows users to rate, review, and discuss a huge range of texts. We drew on data from Goodreads as a potential alternate indicator of texts’ popularity, collecting total number of reviews, total number of ratings, and average overall rating for each novel on the list. \n\n**Project Gutenberg**: We used Project Gutenberg to access the full-text of all novels on the list that are currently in the public domain, or in other words, out of copyright. We chose Project Gutenberg because their eBooks are edited by volunteers, whereas many larger content repositories, like Internet Archive and HathiTrust, only make available machine-generated transcriptions of historical texts, which tend to be less accurate. \n\nOur work creating this dataset not only builds on the work of the OCLC team who compiled the Top 500 list, but on the labor of the thousands of librarians who created records held in WorldCat and VIAF, of the volunteers who transcribed texts for Project Gutenberg and wrote articles for Wikipedia, and of the social media users who reviewed and rated books on Goodreads. \n\n\n## **ACKNOWLEDGING BIAS**\n\nThe Top 500 List provides an unprecedented opportunity to consider what works libraries around the world have on their shelves. This, in turn, serves as an important indicator of books’ continued relevance to readers. As OCLC points out, “libraries offer access to trendy and popular books. But, they don’t keep them on the shelf if they’re not repeatedly requested by their communities over the years.” \n\nAt the same time, there are biases in what gets kept on library shelves, and in which library shelves are being considered. The libraries that OCLC works with are disproportionately located in Europe and North America and OCLC uses cataloging systems developed in English-language contexts. The list is distinctly skewed toward works by White, European and American men, as is much of the history of English literary production, but it is also difficult to tease apart this historical bias from potential compounding biases in the underlying data, in the data collection process, or in library cataloging systems more broadly.\n\nOCLC acknowledges broad biases in the list in a section titled, “Why isn’t the list more diverse?” writing, “The list emphasizes many books that we tend to think of as ‘classics,’ because those are the novels most often translated, retold in different editions, taught and widely distributed in library collections. Because of this, the list tends to reflect more dominant cultural views.” Although OCLC acknowledges this general bias towards works considered classics, more specific forms of bias aren’t made apparent in the list itself, which only includes the title and author for each novel. \n\n\n![](images/top_ten_complete_500.png \"image_tooltip\")\n\nEach of these works and authors, of course, deserves careful consideration in their own right, but by compiling additional information into dataset, we can begin to see some of these biases as well as trends across the list more clearly.\n\n## **WHAT’S IN THE DATA? WHAT MAKES A BOOK A “TOP NOVEL”?**\n\nBy building on OCLC’s initial list and adding a range of information from other databases, we wanted to create a dataset that would offer opportunities to connect metadata analysis and full-text analysis in relation to a historically significant corpus of texts. To this end, we’ve included a brief exploration of the data below, as well as suggested activities, and some ideas for future areas of inquiry.\n\nWe split up our analysis into three portions: metadata analysis, rank analysis, and full-text analysis. You can follow our analysis in the notebook [here](https://drive.google.com/file/d/1gnina8FoyERuin3sDW57GoKh2d6ew1Mt/view?usp=sharing). We first ask questions about the authors represented in the current top 500 list. Then, we compare rankings based on editions, holdings, and GoodReads popularity with the top 500 list. In [another notebook](https://drive.google.com/file/d/1FgPq4nDUmqsaWBkYMEfDEb1OPFuqOYGi/view?usp=sharing), we analyze the full text of works split up by genre.\n\n## **METADATA ANALYSIS**\n\nLet's start by reading our data into a pandas dataframe. A pandas dataframe is a structure used to hold file data. This structure has efficient methods used for manipulating and visualizing data.\n\n::: {.cell execution_count=1}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\nimport pandas as pd\n\ndf = pd.read_csv(\"https://raw.githubusercontent.com/melaniewalsh/responsible-datasets-in-context/main/datasets/top-500-novels/library_top_500.csv\", sep=',', header=0, low_memory=False)\n```\n:::\n\n\nNow, we can answer various questions using this structure, which we've named `df`.\n\nFor example, let's look at counts related to author gender and name.\n\n::: {.cell execution_count=2}\n``` {.python .cell-code}\ndf[\"author_gender\"].value_counts()\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\nauthor_gender\nmale      354\nfemale    145\nName: count, dtype: int64\n```\n:::\n:::\n\n\nWe see that about 70% of authors on the list are male and 30% are female.\n\n::: {.cell execution_count=3}\n``` {.python .cell-code}\ndf[\"author\"].value_counts().head(10)\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\nauthor\nJohn Grisham            19\nCharles Dickens         15\nJohn Steinbeck           8\nC.S. Lewis               8\nJ.K. Rowling             7\nNicholas Sparks          7\nStephen King             7\nLaura Ingalls Wilder     7\nBeverly Cleary           5\nThomas Hardy             5\nName: count, dtype: int64\n```\n:::\n:::\n\n\nAbove are the top 10 authors and the number of times they appear. John Grisham appears a stunning 19 times!\n\nNext, we can delve into some visualization work to understand where authors are from and what timeframe of publication is most represented in the top 500 list.\n\n::: {.cell execution_count=4}\n``` {.python .cell-code}\nimport numpy as np\n\nbins = np.arange(1000, 2060, 50)\nbars = df['pub_year'].plot.hist(bins=bins, edgecolor='w')\nplt.xticks(rotation='vertical');\nplt.xticks(bins);\n```\n\n::: {.cell-output .cell-output-display}\n![](top-500-novels_files/figure-pdf/cell-5-output-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nWe can see that most books on the list were published between 1950 and 2000. Let's take a look at information about the oldest and newest books on the list.\n\n::: {.cell execution_count=5}\n``` {.python .cell-code}\nfrom IPython.display import display\n\nprint(\"Oldest Book(s):\")\ndisplay(df[df[\"pub_year\"]==df[\"pub_year\"].min()])\nprint(\"Newest Book(s):\")\ndisplay(df[df[\"pub_year\"]==df[\"pub_year\"].max()])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOldest Book(s):\nNewest Book(s):\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>top_500_rank</th>\n      <th>title</th>\n      <th>author</th>\n      <th>pub_year</th>\n      <th>orig_lang</th>\n      <th>genre</th>\n      <th>author_birth</th>\n      <th>author_death</th>\n      <th>author_gender</th>\n      <th>author_primary_lang</th>\n      <th>...</th>\n      <th>gr_num_ratings</th>\n      <th>gr_num_reviews</th>\n      <th>gr_avg_rating_rank</th>\n      <th>gr_num_ratings_rank</th>\n      <th>oclc_owi</th>\n      <th>author_viaf</th>\n      <th>gr_url</th>\n      <th>wiki_url</th>\n      <th>pg_eng_url</th>\n      <th>pg_orig_url</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>137</th>\n      <td>138</td>\n      <td>The Tale of Genji</td>\n      <td>Murasaki Shikibu</td>\n      <td>1021</td>\n      <td>Japanese</td>\n      <td>na</td>\n      <td>978?</td>\n      <td>1016?</td>\n      <td>female</td>\n      <td>jpn</td>\n      <td>...</td>\n      <td>13,275</td>\n      <td>1,385</td>\n      <td>430</td>\n      <td>477</td>\n      <td>4.739790e+09</td>\n      <td>95154208</td>\n      <td>https://www.goodreads.com/book/show/7042.The_T...</td>\n      <td>https://en.wikipedia.org/wiki/The_Tale_of_Genji</td>\n      <td>https://www.gutenberg.org/cache/epub/66057/pg6...</td>\n      <td>unavailable</td>\n    </tr>\n  </tbody>\n</table>\n<p>1 rows × 29 columns</p>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>top_500_rank</th>\n      <th>title</th>\n      <th>author</th>\n      <th>pub_year</th>\n      <th>orig_lang</th>\n      <th>genre</th>\n      <th>author_birth</th>\n      <th>author_death</th>\n      <th>author_gender</th>\n      <th>author_primary_lang</th>\n      <th>...</th>\n      <th>gr_num_ratings</th>\n      <th>gr_num_reviews</th>\n      <th>gr_avg_rating_rank</th>\n      <th>gr_num_ratings_rank</th>\n      <th>oclc_owi</th>\n      <th>author_viaf</th>\n      <th>gr_url</th>\n      <th>wiki_url</th>\n      <th>pg_eng_url</th>\n      <th>pg_orig_url</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>401</th>\n      <td>402</td>\n      <td>The Girl on the Train</td>\n      <td>Paula Hawkins</td>\n      <td>2015</td>\n      <td>English</td>\n      <td>na</td>\n      <td>1972</td>\n      <td>ALIVE</td>\n      <td>female</td>\n      <td>eng</td>\n      <td>...</td>\n      <td>2,924,281</td>\n      <td>126,289</td>\n      <td>275</td>\n      <td>26</td>\n      <td>1.893823e+09</td>\n      <td>14277202</td>\n      <td>https://www.goodreads.com/book/show/22557272-t...</td>\n      <td>https://en.wikipedia.org/wiki/The_Girl_on_the_...</td>\n      <td>NA_not-pub-domain</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>480</th>\n      <td>481</td>\n      <td>Go Set a Watchman</td>\n      <td>Harper Lee</td>\n      <td>2015</td>\n      <td>English</td>\n      <td>na</td>\n      <td>1926</td>\n      <td>2016</td>\n      <td>female</td>\n      <td>eng</td>\n      <td>...</td>\n      <td>272,837</td>\n      <td>32,622</td>\n      <td>498</td>\n      <td>209</td>\n      <td>2.283979e+09</td>\n      <td>12431460</td>\n      <td>NaN</td>\n      <td>https://en.wikipedia.org/wiki/Go_Set_a_Watchman</td>\n      <td>NA_not-pub-domain</td>\n      <td>NaN</td>\n    </tr>\n  </tbody>\n</table>\n<p>2 rows × 29 columns</p>\n</div>\n```\n:::\n:::\n\n\nLet's take a look at where the authors are from!\n\n::: {.cell execution_count=6}\n``` {.python .cell-code}\ndf[\"author_nationality\"].value_counts().head(5)\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\nauthor_nationality\nUS    257\nGB    148\nFR     27\nDE     10\nRU     10\nName: count, dtype: int64\n```\n:::\n:::\n\n\nFinally, let's unpack the differences between the GoodReads ratings and the top 500 ratings. First, we should think about how we want to compare the two lists. Given that we have listed rankings by average rating and number of ratings, which metric would be better to use? Would we want to create another metric?\n\nFor our purposes, we decided to use number of ratings, instead of average rating, as OCLC measures popularity by number of holdings, not how much patrons say they enjoy reading the books.\n\n::: {.cell execution_count=7}\n``` {.python .cell-code}\ndef top_5_comparison(col_name):\n  print(df[[\"title\", \"author\", \"top_500_rank\", col_name]].head(5))\n\n  sorted = df.sort_values(by=[col_name])\n  print(sorted[[\"title\", \"author\", \"top_500_rank\", col_name]].head(5))\n\ntop_5_comparison(\"gr_num_ratings_rank\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                title                  author  top_500_rank  \\\n0                         Don Quixote     Miguel de Cervantes             1   \n1    Alice's Adventures in Wonderland           Lewis Carroll             2   \n2  The Adventures of Huckleberry Finn              Mark Twain             3   \n3        The Adventures of Tom Sawyer              Mark Twain             4   \n4                     Treasure Island  Robert Louis Stevenson             5   \n\n   gr_num_ratings_rank  \n0                  211  \n1                  133  \n2                   68  \n3                   88  \n4                  145  \n                                     title               author  top_500_rank  \\\n44   Harry Potter and the Sorcerer's Stone         J.K. Rowling            45   \n172                       The Hunger Games      Suzanne Collins           173   \n131                               Twilight      Stephenie Meyer           132   \n28                   To Kill a Mockingbird           Harper Lee            29   \n33                        The Great Gatsby  F. Scott Fitzgerald            34   \n\n     gr_num_ratings_rank  \n44                     1  \n172                    2  \n131                    3  \n28                     4  \n33                     5  \n```\n:::\n:::\n\n\nAbove you can see that the GoodReads rankings and the top 500 rankings aren't very aligned! What factors affect popularity on GoodReads compared to OCLC?\n\n::: {.cell execution_count=8}\n``` {.python .cell-code}\nimport math\n\ndef print_rankings(d, col_name):\n    rank_B = d[col_name]\n    rank_A = d[\"top_500_rank\"]\n    title = d[\"title\"]\n    points_moved = 0\n    if (math.isnan(rank_B)):\n      points_moved = 501\n    else:\n      if rank_B > int(rank_A):\n          points_moved = rank_B - rank_A\n          print(f\"\\u001b[31m ▼ -{int(points_moved)} {title}\")\n      elif rank_B < rank_A:\n          points_moved = rank_A - rank_B\n          print(f\"\\u001b[32m ▲ +{int(points_moved)} {title}\")\n      else:\n          print(f\"\\u001b[30m ● {int(points_moved)} {title}\")\n    d[\"points_moved\"] = int(points_moved)\n    return d\n\ndf = df.apply(lambda d: print_rankings(d, \"gr_num_ratings_rank\"), axis=1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n ▼ -210 Don Quixote\n ▼ -131 Alice's Adventures in Wonderland\n ▼ -65 The Adventures of Huckleberry Finn\n ▼ -84 The Adventures of Tom Sawyer\n ▼ -140 Treasure Island\n ▼ -2 Pride and Prejudice\n ▼ -39 Wuthering Heights\n ▼ -32 Jane Eyre\n ▼ -125 Moby Dick\n ▼ -85 The Scarlet Letter\n ▼ -197 Gulliver's Travels\n ▼ -266 The Pilgrim's Progress\n ▼ -85 A Christmas Carol\n ▼ -214 David Copperfield\n ▼ -71 A Tale of Two Cities\n ▼ -22 Little Women\n ▼ -86 Great Expectations\n ▲ +8 The Hobbit, or, There and Back Again\n ▼ -35 Frankenstein, or, the Modern Prometheus\n ▼ -149 Oliver Twist\n ▼ -209 Uncle Tom's Cabin\n ▼ -72 Crime and Punishment\n ▼ -159 Madame Bovary: Patterns of Provincial life\n ▼ -69 The Return of the King\n ▼ -42 Dracula\n ▼ -160 The Three Musketeers\n ▼ -16 Brave New World\n ▼ -155 War and Peace\n ▲ +25 To Kill a Mockingbird\n ▼ -122 The Wizard of Oz\n ▼ -73 Les Misérables\n ▼ -43 The Secret Garden\n ▲ +21 Animal Farm\n ▲ +29 The Great Gatsby\n ▼ -4 The Little Prince\n ▼ -124 The Call of the Wild\n ▼ -444 20,000 Leagues Under the Sea\n ▼ -59 Anna Karenina\n ▼ -193 The Wind in the Willows\n ▼ -17 The Picture of Dorian Gray\n ▼ -50 The Grapes of Wrath\n ▼ -32 Sense and Sensibility\n ▼ -279 The Last of the Mohicans\n ▼ -159 Tess of the d'Urbervilles\n ▲ +44 Harry Potter and the Sorcerer's Stone\n ▼ -193 Heidi\n ▼ -242 Ulysses\n ▼ -192 The Complete Sherlock Holmes\n ▼ -41 The Count of Monte Cristo\n ▼ -27 The Old Man and the Sea\n ▲ +22 The Lion, the Witch, and the Wardrobe\n ▼ -184 The Hunchback of Notre Dame\n ▼ -293 Pinocchio\n ▼ -28 One Hundred Years of Solitude\n ▼ -274 Ivanhoe\n ▼ -259 The Red Badge of Courage\n ▼ -24 Anne of Green Gables\n ▼ -146 Black Beauty\n ▼ -120 Peter Pan\n ▼ -127 A Farewell to Arms\n ▼ -349 The House of the Seven Gables\n ▲ +35 Lord of the Flies\n ▼ -233 The Prince and the Pauper\n ▼ -209 A Portrait of the Artist as a Young Man\n ▼ -367 Lord Jim\n ▲ +55 Harry Potter and the Chamber of Secrets\n ▼ -287 The Red & the Black\n ▼ -11 The Stranger\n ▼ -116 The Trial\n ▼ -224 Lady Chatterley's Lover\n ▼ -298 Kidnapped: The Adventures of David Balfour\n ▲ +56 The Catcher in the Rye\n ▲ +38 Fahrenheit 451\n ▼ -164 A Journey to the Center of the Earth\n ▼ -213 Vanity Fair\n ▼ -75 All Quiet on the Western Front\n ▲ +6 Gone with the Wind\n ▼ -201 My Ántonia\n ▲ +47 Of Mice and Men\n ▼ -405 The Vicar of Wakefield\n ▼ -235 A Connecticut Yankee in King Arthur's Court\n ▼ -164 White Fang\n ▼ -255 Fathers and Sons\n ▼ -242 Doctor Zhivago\n ▼ -324 The Decameron\n ▲ +79 Nineteen Eighty-Four\n ▼ -187 The Jungle\n ▲ +51 The Da Vinci Code\n ▼ -26 Persuasion\n ▼ -88 Mansfield Park\n ▼ -114 Candide\n ▼ -107 For Whom the Bell Tolls\n ▼ -178 Far from the Madding Crowd\n ▲ +66 The Fellowship of the Ring\n ▼ -319 The Return of the Native\n ▼ -294 Sons and Lovers\n ▲ +52 Charlotte's Web\n ▼ -214 The Swiss Family Robinson\n ▼ -210 Bleak House\n ▼ -278 Père Goriot\n ▼ -252 Utopia\n ▼ -327 The History of Tom Jones, a Foundling\n ▲ +94 Harry Potter and the Prisoner of Azkaban\n ▼ -314 Kim\n ▼ -150 The Sound and the Fury\n ▲ +92 Harry Potter and the Goblet of Fire\n ▼ -278 The Mill on the Floss\n ▲ +36 A Wrinkle in Time\n ▼ -72 The Hound of the Baskervilles\n ▲ +27 The Two Towers\n ▼ -78 The War of the Worlds\n ▼ -152 Middlemarch\n ▼ -146 The Age of Innocence\n ▼ -6 The Color Purple\n ▼ -50 Northanger Abbey\n ▼ -24 East of Eden\n ▼ -45 On the Road\n ▲ +19 Catch-22\n ▼ -105 Around the World in Eighty Days\n ▼ -244 Hard Times\n ▼ -37 Beloved\n ▼ -71 Mrs. Dalloway\n ▼ -131 To the Lighthouse\n ▼ -14 The Magician's Nephew\n ▲ +108 Harry Potter and the Order of the Phoenix\n ▼ -29 The Sun Also Rises\n ▼ -96 The Good Earth\n ▼ -212 Silas Marner\n ▼ -15 Love in the Time of Cholera\n ▲ +5 Rebecca\n ▼ -230 Jude the Obscure\n ▲ +129 Twilight\n ▼ -215 A Passage to India\n ▼ -84 The Plague\n ▼ -266 Nicholas Nickleby\n ▼ -93 The Pearl\n ▼ -155 Ethan Frome\n ▼ -339 The Tale of Genji\n ▲ +105 The Giver\n ▲ +116 The Alchemist\n ▼ -146 The Strange Case of Dr. Jekyll and Mr. Hyde\n ▼ -52 Robinson Crusoe\n ▼ -138 Tender is the Night\n ▼ -112 The Idiot\n ▼ -22 Hatchet\n ▲ +124 The Kite Runner\n ▲ +36 One Flew Over the Cuckoo's Nest\n ▼ -199 The Portrait of a Lady\n ▲ +84 The Outsiders\n ▼ -272 Ben-Hur\n ▼ -222 The Mayor of Casterbridge\n ▼ -204 Cry, The Beloved Country\n ▼ -53 The Last Battle\n ▼ -308 Captains Courageous\n ▼ -219 The Castle\n ▲ +76 The Metamorphosis\n ▼ -237 The Magic Mountain (Der Zauberberg)\n ▲ +10 James and the Giant Peach\n ▼ -18 The Horse and His Boy\n ▲ +140 Angels & Demons\n ▲ +12 The Voyage of the Dawn Treader\n ▲ +77 The Bell Jar\n ▼ -268 Women in Love\n ▼ -279 The Yearling\n ▼ -223 O Pioneers!\n ▲ +125 The Handmaid's Tale\n ▼ -165 The Moonstone\n ▼ -292 The Old Curiosity Shop\n ▼ -229 Little Dorrit\n ▲ +14 Prince Caspian: The Return to Narnia\n ▼ -237 Sister Carrie\n ▼ -26 The Silver Chair\n ▲ +171 The Hunger Games\n ▼ -183 This Side of Paradise\n ▼ -282 Eugénie Grandet\n ▼ -206 Of Human Bondage\n ▼ -320 Dream of the Red Chamber\n ▲ +127 Life of Pi\n ▲ +166 Harry Potter and the Deathly Hallows\n ▼ -68 Invisible Man\n ▼ -70 Steppenwolf\n ▼ -104 The Sorrows of Young Werther\n ▲ +46 Bridge to Terabithia\n ▼ -60 The Invisible Man\n ▲ +112 Holes\n ▲ +81 Siddhartha\n ▲ +37 A Tree Grows in Brooklyn\n ▼ -94 Through the Looking-Glass, and What Alice Found There\n ▲ +66 In Cold Blood\n ▼ -25 The House of the Spirits\n ▼ -259 Adam Bede\n ▼ -280 The Betrothed\n ▲ +162 The Book Thief\n ▲ +14 Their Eyes Were Watching God\n ▼ -106 One Day in the Life of Ivan Denisovich\n ▼ -239 The Sea Wolf\n ▲ +182 Catching Fire\n ▼ -97 Roll of Thunder, Hear My Cry\n ▼ -220 Death Comes for the Archbishop\n ▼ -123 The House of Mirth\n ▼ -174 Light in August\n ▼ -237 The Pickwick Papers\n ▼ -292 Remembrance of Things Past\n ▼ -295 Barchester Towers and the Warden\n ▼ -219 The Bridge of San Luis Rey\n ▲ +176 The Help\n ▲ +80 Murder on the Orient Express\n ▲ +172 The Lovely Bones\n ▼ -171 The Appeal\n ▼ -261 Dombey And Son\n ▲ +149 Slaughterhouse-Five\n ▼ -209 An American Tragedy\n ▼ -9 The Bluest Eye\n ▲ +1 Little House In the Big Woods\n ▼ -22 Pippi Longstocking\n ▼ -201 Germinal\n ▼ -89 The Heart Is a Lonely Hunter\n ▼ -52 The Woman In White\n ▼ -183 Absalom, Absalom!\n ▼ -111 A Painted House\n ▲ +200 The Girl With the Dragon Tattoo\n ▼ -31 A Room With a View\n ▲ +76 Watership Down\n ▲ +182 Memoirs of a Geisha\n ▼ -215 Our Mutual Friend\n ▼ -229 Babbitt\n ▼ -159 The Red Pony\n ▼ -143 All the King's Men\n ▲ +59 Things Fall Apart\n ▼ -240 Lorna Doone\n ▼ -164 Johnny Tremain\n ▼ -10 Anne of Avonlea\n ▲ +26 Tuck Everlasting\n ▲ +88 The BFG\n ▼ -45 Cannery Row\n ▲ +117 The Joy Luck Club\n ▲ +37 The Silmarillion\n ▼ -30 Roots\n ▲ +38 Little House on the Prairie\n ▼ -80 Native Son\n ▼ -52 Stuart Little\n ▼ -181 Cross Fire\n ▼ -169 The Power and the Glory\n ▲ +130 A Clockwork Orange\n ▲ +19 The Phantom of the Opera\n ▲ +27 The Martian Chronicles\n ▲ +155 The Road\n ▼ -239 The Way of All Flesh\n ▼ -251 Diary of a Wimpy Kid: The Long Haul\n ▼ -108 Villette\n ▲ +191 The Curious Incident of the Dog In the Night-Time\n ▼ -135 The Mysterious Island\n ▼ -50 Song of Solomon\n ▼ -198 Nana\n ▼ -160 Quo Vadis\n ▼ -192 Main Street\n ▲ +170 Matilda\n ▲ +162 Lolita\n ▲ +196 Paper Towns\n ▼ -176 Sounder\n ▲ +34 Are You There God? It's Me, Margaret\n ▲ +212 The Notebook\n ▲ +29 From the Mixed-Up Files of Mrs. Basil E. Frankweiler\n ▲ +96 Atlas Shrugged\n ▲ +81 The Fountainhead\n ▲ +134 Number the Stars\n ▲ +141 The Firm\n ▼ -108 Swann's Way\n ▲ +208 Ender's Game\n ▲ +98 The Name of the Rose\n ▲ +169 A Time to Kill\n ▲ +220 Water for Elephants\n ▲ +131 The Time Machine\n ▲ +226 Eragon\n ▲ +231 The Hitchhiker's Guide to the Galaxy\n ▼ -161 Buddenbrooks\n ▲ +221 A Thousand Splendid Suns\n ▲ +6 The Witch of Blackbird Pond\n ▲ +215 And Then There Were None\n ▲ +49 A Separate Peace\n ▲ +232 Breaking Dawn\n ▲ +20 As I Lay Dying\n ▲ +194 The Girl Who Played With Fire\n ▲ +121 Where the Red Fern Grows\n ▼ -131 Le Morte D'Arthur\n ▲ +267 Mockingjay\n ▲ +181 The Pillars of the Earth\n ▼ -202 Persian Letters\n ▲ +136 The Client\n ▼ -34 Sula\n ▲ +15 Tales of a Fourth Grade Nothing\n ▼ -78 The Merry Adventures of Robin Hood of Great Renown In Nottinghamshire\n ▼ -91 Tortilla Flat\n ▼ -179 Look Homeward, Angel\n ▼ -185 The Mystery of Edwin Drood\n ▼ -6 Brideshead Revisited\n ▲ +138 The Pelican Brief\n ▲ +157 Atonement\n ▼ -157 Washington Square\n ▲ +129 Like Water for Chocolate\n ▲ +246 The Golden Compass\n ▲ +236 The Secret Life of Bees\n ▲ +297 The Fault In Our Stars\n ▼ -164 Nostromo\n ▼ -173 Finnegans Wake\n ▼ -22 The Brethren\n ▲ +189 Coraline\n ▲ +165 Heart of Darkness\n ▼ -8 On the Banks of Plum Creek\n ▼ -115 Rebecca of Sunnybrook Farm\n ▼ -168 The Ambassadors\n ▼ -146 The Secret Agent\n ▲ +66 The House on Mango Street\n ▼ -51 Go Tell It on the Mountain\n ▲ +18 The Testament\n ▲ +102 The Clan of the Cave Bear\n ▼ -87 Cranford\n ▲ +98 Because of Winn-Dixie\n ▼ -33 My Side of the Mountain\n ▲ +125 The Runaway Jury\n ▼ -23 The Mouse and the Motorcycle\n ▲ +193 The Lost Symbol\n ▼ -141 The Forsyte Saga\n ▲ +301 Gone Girl\n ▲ +300 The Lightning Thief\n ▼ -170 The Last Days of Pompeii\n ▲ +92 The Reader\n ▼ -63 Caddie Woodlawn\n ▲ +88 The Tale of Despereaux\n ▲ +220 The Girl Who Kicked the Hornet's Nest\n ▼ -76 Dear Mr. Henshaw\n ▼ -10 The Killer Angels\n ▲ +88 Chronicle of a Death Foretold\n ▲ +222 The Five People You Meet In Heaven\n ▲ +160 The Master and Margarita\n ▼ -90 Winesburg, Ohio\n ▼ -107 P Is for Peril\n ▲ +268 My Sister's Keeper\n ▼ -143 Barnaby Rudge\n ▲ +4 Howards End\n ▲ +14 The Broker\n ▲ +8 The Camel Club\n ▼ -120 The Rainbow\n ▼ -23 The Man In the Iron Mask\n ▲ +62 Mary Poppins\n ▲ +210 Artemis Fowl\n ▲ +216 Dear John\n ▲ +123 Cold Mountain\n ▲ +228 Flowers for Algernon\n ▼ -31 The Dark Is Rising\n ▼ -102 Resurrection\n ▲ +22 Fearless Fourteen\n ▼ -139 A Sentimental Journey Through France and Italy\n ▲ +11 The King of Torts\n ▲ +216 The Graveyard Book\n ▼ -16 The Quiet American\n ▲ +82 The Chamber\n ▲ +74 The English Patient\n ▲ +110 Snow Falling on Cedars\n ▲ +21 The Long Winter\n ▲ +20 Sarah, Plain and Tall\n ▼ -44 Cross Country\n ▲ +56 The Spy Who Came In from the Cold\n ▲ +331 A Game of Thrones\n ▲ +189 The Thorn Birds\n ▲ +45 Old Yeller\n ▲ +7 Ramona Quimby, Age 8\n ▼ -15 Death In Venice\n ▲ +19 By the Shores of Silver Lake\n ▲ +235 Inferno\n ▲ +104 Schindler's List\n ▲ +151 Jonathan Livingston Seagull\n ▲ +266 The Stand\n ▲ +55 The Last Juror\n ▲ +30 Shiloh\n ▲ +267 Girl With a Pearl Earring\n ▲ +167 The Murder of Roger Ackroyd\n ▲ +300 It\n ▲ +136 The Rainmaker\n ▲ +272 The Poisonwood Bible\n ▲ +68 The Indian in the Cupboard\n ▲ +71 The Maltese Falcon\n ▼ -84 The Warden\n ▲ +35 The Summons\n ▼ -26 Encyclopedia Brown: Boy Detective\n ▲ +339 The Time Traveler's Wife\n ▼ -5 The Incredible Journey\n ▲ +103 Daughter of Fortune\n ▼ -38 Shirley\n ▲ +85 Bud, Not Buddy\n ▲ +12 The Horse Whisperer\n ▲ +93 The Street Lawyer\n ▲ +95 Nausea\n ▼ -36 To Have and Have Not\n ▲ +70 The Bridges of Madison County\n ▲ +136 Anne of the Island\n ● 0 The Winter of Our Discontent\n ▲ +339 The Shining\n ▲ +99 The Tenant of Wildfell Hall\n ▼ -3 First Family\n ▲ +111 The Partner\n ▲ +376 The Girl on the Train\n ▼ -62 The Black Arrow: A Tale of the Two Roses\n ▼ -90 The Rise of Silas Lapham\n ▲ +153 The Choice\n ▼ -82 The Virginian: A Horseman of the Plains\n ▲ +307 A Walk to Remember\n ▲ +350 The Maze Runner\n ▲ +176 The Westing Game\n ▲ +11 Misty of Chincoteague\n ▲ +142 Diary of a Wimpy Kid: The Last Straw\n ▲ +19 King Solomon's Mines\n ▼ -56 The Princess of Cleves\n ▼ -14 Jacob Have I Loved\n ▲ +158 Mrs. Frisby and the Rats of NIMH\n ▲ +300 Misery\n ▲ +167 The Cider House Rules\n ▼ -28 King of the Wind\n ▲ +109 The Once and Future King\n ▲ +254 The Witches\n ▲ +264 The Subtle Knife\n ▲ +118 When You Reach Me\n ▲ +310 Carrie\n ▼ -30 The Moon and Sixpence\n ▼ -51 The Higher Power of Lucky\n ▼ -65 Looking Backward, 2000-1887\n ▼ -39 The Wings of the Dove\n ▼ -55 The Summer of the Swans\n ▲ +40 Dangerous Liaisons\n ▲ +346 Jurassic Park\n ▲ +219 The Absolutely True Diary of a Part-time Indian\n ▲ +19 The Grey King\n ▲ +13 The Leopard\n ▲ +75 The Mammoth Hunters\n ▲ +84 The Trumpet of the Swan\n ▲ +263 The Lucky One\n ▲ +82 These Happy Golden Years\n ▼ -51 Arrowsmith\n ▲ +62 Julie of the Wolves\n ▲ +286 The Screwtape Letters\n ▲ +127 The Fall\n ▲ +226 The No. 1 Ladies' Detective Agency\n ▲ +5 Worst Case\n ▼ -15 Lost Horizon\n ▲ +317 The Gunslinger\n ▼ -38 The Slave Dancer\n ▲ +429 Harry Potter and the Half-Blood Prince\n ▲ +287 Inkheart\n ▲ +16 Ramona and her Father\n ▲ +159 Inkspell\n ▲ +85 Ramona the Pest\n ▲ +189 Walk Two Moons\n ▲ +384 Miss Peregrine's Home for Peculiar Children\n ▲ +54 The Chocolate War\n ▲ +120 Sophie's Choice\n ▲ +403 Looking for Alaska\n ▲ +240 Breakfast at Tiffany's\n ▲ +62 The Razor's Edge\n ▲ +201 Dreamcatcher\n ▲ +127 Orlando\n ▲ +270 The Things they Carried\n ▲ +125 Little Town on the Prairie\n ▲ +202 Nights in Rodanthe\n ▲ +290 The Amber Spyglass\n ▲ +157 The Miraculous Journey of Edward Tulane\n ▲ +103 Flatland\n ▲ +350 Diary of a Wimpy Kid\n ▲ +338 The Memory Keeper's Daughter\n ▲ +203 The Wedding\n ▲ +278 Fried Green Tomatoes at the Whistle-Stop Cafe\n ▲ +103 The Cricket in Times Square\n ▲ +270 The Phantom Tollbooth\n ▼ -13 Rob Roy\n ▲ +209 The Death of Ivan Ilych\n ▲ +34 Alex Cross's Trial\n ▼ -22 Kenilworth\n ▲ +16 The Life and Opinions of Tristram Shandy\n ▲ +282 The Remains of the Day\n ▼ -14 M.C. Higgins, The Great\n ▲ +5 Call It Courage\n ▲ +272 Go Set a Watchman\n ▲ +77 Bleachers\n ▲ +9 Elijah of Buxton\n ▲ +37 Swimsuit\n ▲ +321 Cat's Cradle\n ▲ +35 The Caine Mutiny\n ▲ +45 The Heart of the Matter\n ▲ +170 Harriet, the Spy\n ▲ +55 Darkness at Noon\n ▲ +302 A Prayer for Owen Meany\n ▲ +294 The God of Small Things\n ▲ +130 The Associate\n ▲ +369 The Shack\n ▲ +45 The Naked and the Dead\n ▲ +419 The Sea of Monsters\n ▲ +306 Stranger in a Strange Land\n ▲ +220 Vision in White\n ▲ +53 The Whipping Boy\n ▲ +398 Room\n ▲ +378 Deception Point\n```\n:::\n:::\n\n\nLet's see which novels had the most movement up or down!\n\n::: {.cell execution_count=9}\n``` {.python .cell-code}\nsorted = df.sort_values(by=['points_moved'])\nprint(sorted[[\"title\", \"author\", \"points_moved\", \"top_500_rank\", \"gr_num_ratings_rank\"]].head(10).to_string(index=False))\n\nsorted = df.sort_values(by=['points_moved'], ascending=False)\nprint(sorted[[\"title\", \"author\", \"points_moved\", \"top_500_rank\", \"gr_num_ratings_rank\"]].head(10).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                        title                   author  points_moved  top_500_rank  gr_num_ratings_rank\n The Winter of Our Discontent           John Steinbeck             0           397                  397\nLittle House In the Big Woods     Laura Ingalls Wilder             1           214                  213\n          Pride and Prejudice              Jane Austen             2             6                    8\n                 First Family           David Baldacci             3           400                  403\n            The Little Prince Antoine de Saint-Exupéry             4            35                   39\n                  Howards End             E.M. Forster             4           340                  336\n                      Rebecca        Daphne Du Maurier             5           130                  125\n              Call It Courage         Armstrong Sperry             5           480                  475\n       The Incredible Journey          Sheila Burnford             5           387                  392\n                   Worst Case          James Patterson             5           443                  438\n                                      title           author  points_moved  top_500_rank  gr_num_ratings_rank\n               20,000 Leagues Under the Sea      Jules Verne           444            37                  481\n     Harry Potter and the Half-Blood Prince     J.K. Rowling           429           447                   18\n                        The Sea of Monsters     Rick Riordan           419           495                   76\n                     The Vicar of Wakefield Oliver Goldsmith           405            80                  485\n                         Looking for Alaska       John Green           403           456                   53\n                                       Room    Emma Donoghue           398           499                  101\nMiss Peregrine's Home for Peculiar Children     Ransom Riggs           384           453                   69\n                            Deception Point        Dan Brown           378           500                  122\n                      The Girl on the Train    Paula Hawkins           376           402                   26\n                                  The Shack William P. Young           369           493                  124\n```\n:::\n:::\n\n\nAbove we see that Steinbeck's *The Winter of Our Discontent*, stayed at the same ranking of 397. *Pride and Prejudice* remained quite high as well.\n\n*20,000 Leagues Under the Sea* dropped the most, from rank 37 in the top 500 list, to rank 481 in the goodreads list! *Harry Potter and The Half-Blood Prince* and *The Sea of Monsters* rose the most.\n\ndf['points_moved'].mean()\n\n::: {.cell execution_count=10}\n``` {.python .cell-code}\ndf['points_moved'].mean()\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```\n137.016\n```\n:::\n:::\n\n\nLet's take a look at some of these metrics for rankings based on number of editions and total holdings.\n\n::: {.cell execution_count=11}\n``` {.python .cell-code}\ndf = df.apply(lambda d: print_rankings(d, \"oclc_editions_rank\"), axis=1)\n\ndf = df[df[\"points_moved\"] <= 500]\ntop_5_comparison(\"oclc_editions_rank\")\n\ndf['points_moved'].mean()\nsmaller_df = df.head(10)\nsmaller_df['points_moved'].mean()\n\ndf = df.apply(lambda d: print_rankings(d, \"oclc_holdings_rank\"), axis=1)\n\ntop_5_comparison(\"oclc_holdings_rank\")\n\ndf['points_moved'].mean()\nsmaller_df = df.head(10)\nsmaller_df['points_moved'].mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n ● 0 Don Quixote\n ▼ -31 Alice's Adventures in Wonderland\n ▼ -3 The Adventures of Huckleberry Finn\n ▼ -3 The Adventures of Tom Sawyer\n ▲ +3 Treasure Island\n ▲ +3 Pride and Prejudice\n ▼ -4 Wuthering Heights\n ▲ +3 Jane Eyre\n ▼ -10 Moby Dick\n ▼ -17 The Scarlet Letter\n ▼ -24 Gulliver's Travels\n ▼ -9 The Pilgrim's Progress\n ▲ +5 A Christmas Carol\n ▼ -2 David Copperfield\n ▼ -2 A Tale of Two Cities\n ▼ -9 Little Women\n ▼ -1 Great Expectations\n ▼ -178 The Hobbit, or, There and Back Again\n ▼ -12 Frankenstein, or, the Modern Prometheus\n ▲ +11 Oliver Twist\n ▲ +1 Uncle Tom's Cabin\n ▼ -135 Crime and Punishment\n ▼ -95 Madame Bovary: Patterns of Provincial life\n ▼ -390 The Return of the King\n ▼ -13 Dracula\n ▲ +16 The Three Musketeers\n ▼ -74 Brave New World\n ▼ -186 War and Peace\n ▼ -110 To Kill a Mockingbird\n ▼ -101 The Wizard of Oz\n ▲ +7 Les Misérables\n ▼ -36 The Secret Garden\n ▼ -7 Animal Farm\n ▼ -12 The Great Gatsby\n ▲ +13 The Little Prince\n ▼ -13 The Call of the Wild\n ▲ +8 20,000 Leagues Under the Sea\n ▲ +10 Anna Karenina\n ▼ -27 The Wind in the Willows\n ▲ +8 The Picture of Dorian Gray\n ▼ -50 The Grapes of Wrath\n ▼ -14 Sense and Sensibility\n ▼ -2 The Last of the Mohicans\n ▼ -9 Tess of the d'Urbervilles\n ▼ -109 Harry Potter and the Sorcerer's Stone\n ▲ +5 Heidi\n ▼ -10 Ulysses\n ▼ -332 The Complete Sherlock Holmes\n ▲ +5 The Count of Monte Cristo\n ▲ +3 The Old Man and the Sea\n ▼ -124 The Lion, the Witch, and the Wardrobe\n ▲ +26 The Hunchback of Notre Dame\n ▼ -227 Pinocchio\n ▼ -295 One Hundred Years of Solitude\n ▲ +43 Ivanhoe\n ▼ -81 The Red Badge of Courage\n ▼ -39 Anne of Green Gables\n ▼ -28 Black Beauty\n ▼ -132 Peter Pan\n ▼ -43 A Farewell to Arms\n ▼ -46 The House of the Seven Gables\n ▼ -57 Lord of the Flies\n ▼ -11 The Prince and the Pauper\n ▼ -26 A Portrait of the Artist as a Young Man\n ● 0 Lord Jim\n ▼ -106 Harry Potter and the Chamber of Secrets\n ▲ +7 The Stranger\n ▲ +33 The Trial\n ▼ -43 Lady Chatterley's Lover\n ▼ -423 Kidnapped: The Adventures of David Balfour\n ▼ -76 The Catcher in the Rye\n ▼ -63 Fahrenheit 451\n ▲ +20 A Journey to the Center of the Earth\n ▲ +16 Vanity Fair\n ▲ +5 All Quiet on the Western Front\n ▼ -87 Gone with the Wind\n ▼ -103 My Ántonia\n ▼ -13 Of Mice and Men\n ▲ +66 The Vicar of Wakefield\n ▲ +6 A Connecticut Yankee in King Arthur's Court\n ▲ +32 White Fang\n ▼ -43 Fathers and Sons\n ▼ -220 Doctor Zhivago\n ▲ +62 The Decameron\n ▼ -42 Nineteen Eighty-Four\n ▼ -79 The Jungle\n ▼ -111 The Da Vinci Code\n ▲ +85 Persuasion\n ▲ +27 Mansfield Park\n ▲ +43 Candide\n ▼ -16 For Whom the Bell Tolls\n ▼ -12 Far from the Madding Crowd\n ▼ -195 The Fellowship of the Ring\n ▼ -32 The Return of the Native\n ▼ -18 Sons and Lovers\n ▼ -141 Charlotte's Web\n ▲ +9 The Swiss Family Robinson\n ▲ +27 Bleak House\n ▲ +58 Père Goriot\n ▲ +32 Utopia\n ▲ +35 The History of Tom Jones, a Foundling\n ▼ -76 Harry Potter and the Prisoner of Azkaban\n ▲ +22 Kim\n ▼ -79 The Sound and the Fury\n ▼ -102 Harry Potter and the Goblet of Fire\n ▲ +34 The Mill on the Floss\n ▼ -161 A Wrinkle in Time\n ▲ +49 The Hound of the Baskervilles\n ▼ -228 The Two Towers\n ▲ +9 The War of the Worlds\n ▲ +15 Middlemarch\n ▼ -38 The Age of Innocence\n ▼ -122 The Color Purple\n ▲ +21 Northanger Abbey\n ▼ -90 East of Eden\n ▼ -77 On the Road\n ▼ -65 Catch-22\n ▲ +89 Around the World in Eighty Days\n ▲ +43 Hard Times\n ▼ -105 Beloved\n ● 0 Mrs. Dalloway\n ▼ -6 To the Lighthouse\n ▼ -110 The Magician's Nephew\n ▼ -94 Harry Potter and the Order of the Phoenix\n ▲ +22 The Sun Also Rises\n ▼ -80 The Good Earth\n ▲ +70 Silas Marner\n ▼ -81 Love in the Time of Cholera\n ▼ -8 Rebecca\n ▼ -12 Jude the Obscure\n ▼ -131 Twilight\n ▼ -25 A Passage to India\n ▲ +49 The Plague\n ▼ -36 Nicholas Nickleby\n ▲ +43 The Pearl\n ▼ -41 Ethan Frome\n ▲ +28 The Tale of Genji\n ▼ -142 The Giver\n ▼ -15 The Alchemist\n ▲ +60 The Strange Case of Dr. Jekyll and Mr. Hyde\n ▲ +33 Robinson Crusoe\n ▼ -34 Tender is the Night\n ▲ +23 The Idiot\n ▼ -201 Hatchet\n ▼ -111 The Kite Runner\n ▼ -77 One Flew Over the Cuckoo's Nest\n ▲ +15 The Portrait of a Lady\n ▼ -91 The Outsiders\n ▲ +80 Ben-Hur\n ▲ +9 The Mayor of Casterbridge\n ▼ -57 Cry, The Beloved Country\n ▼ -160 The Last Battle\n ▲ +9 Captains Courageous\n ▲ +75 The Castle\n ▲ +119 The Metamorphosis\n ▲ +93 The Magic Mountain (Der Zauberberg)\n ▼ -115 James and the Giant Peach\n ▼ -105 The Horse and His Boy\n ▼ -111 The Voyage of the Dawn Treader\n ▼ -60 The Bell Jar\n ▼ -4 Women in Love\n ▼ -103 The Yearling\n ▼ -79 O Pioneers!\n ▼ -50 The Handmaid's Tale\n ▲ +51 The Moonstone\n ▲ +69 The Old Curiosity Shop\n ▲ +71 Little Dorrit\n ▼ -197 Prince Caspian: The Return to Narnia\n ▼ -3 Sister Carrie\n ▼ -75 The Silver Chair\n ▼ -220 The Hunger Games\n ▼ -41 This Side of Paradise\n ▲ +132 Eugénie Grandet\n ▼ -13 Of Human Bondage\n ▲ +60 Dream of the Red Chamber\n ▼ -53 Life of Pi\n ▼ -98 Harry Potter and the Deathly Hallows\n ▼ -79 Invisible Man\n ▲ +97 Steppenwolf\n ▲ +167 The Sorrows of Young Werther\n ▼ -139 Bridge to Terabithia\n ▲ +73 The Invisible Man\n ▼ -138 Holes\n ▲ +110 Siddhartha\n ▼ -97 A Tree Grows in Brooklyn\n ▲ +154 Through the Looking-Glass, and What Alice Found There\n ▼ -111 In Cold Blood\n ▼ -2 The House of the Spirits\n ▲ +85 Adam Bede\n ▲ +153 The Betrothed\n ▼ -94 The Book Thief\n ▼ -114 Their Eyes Were Watching God\n ▼ -130 One Day in the Life of Ivan Denisovich\n ▲ +145 The Sea Wolf\n ▼ -197 Catching Fire\n ▼ -179 Roll of Thunder, Hear My Cry\n ▼ -67 Death Comes for the Archbishop\n ▼ -2 The House of Mirth\n ▼ -47 Light in August\n ▲ +70 The Pickwick Papers\n ▲ +59 Remembrance of Things Past\n ▼ -291 Barchester Towers and the Warden\n ▲ +8 The Bridge of San Luis Rey\n ▼ -108 The Help\n ▲ +42 Murder on the Orient Express\n ▼ -135 The Lovely Bones\n ▼ -176 The Appeal\n ▲ +115 Dombey And Son\n ▼ -173 Slaughterhouse-Five\n ▲ +9 An American Tragedy\n ▼ -57 The Bluest Eye\n ▼ -101 Little House In the Big Woods\n ▲ +29 Pippi Longstocking\n ▲ +133 Germinal\n ▼ -12 The Heart Is a Lonely Hunter\n ▲ +77 The Woman In White\n ▼ -67 Absalom, Absalom!\n ▼ -144 A Painted House\n ▼ -53 The Girl With the Dragon Tattoo\n ▲ +40 A Room With a View\n ▼ -73 Watership Down\n ▼ -29 Memoirs of a Geisha\n ▲ +101 Our Mutual Friend\n ▲ +56 Babbitt\n ▲ +77 The Red Pony\n ▼ -43 All the King's Men\n ▼ -1 Things Fall Apart\n ▲ +110 Lorna Doone\n ▼ -121 Johnny Tremain\n ▲ +12 Anne of Avonlea\n ▼ -138 Tuck Everlasting\n ▼ -120 The BFG\n ▼ -20 Cannery Row\n ▼ -97 The Joy Luck Club\n ▲ +39 The Silmarillion\n ▼ -127 Roots\n ▼ -77 Little House on the Prairie\n ▼ -42 Native Son\n ▼ -103 Stuart Little\n ▼ -242 Cross Fire\n ▲ +87 The Power and the Glory\n ▲ +39 A Clockwork Orange\n ▲ +76 The Phantom of the Opera\n ▲ +11 The Martian Chronicles\n ▼ -104 The Road\n ▲ +75 The Way of All Flesh\n ▼ -176 Diary of a Wimpy Kid: The Long Haul\n ▲ +110 Villette\n ▼ -37 The Curious Incident of the Dog In the Night-Time\n ▲ +197 The Mysterious Island\n ▼ -50 Song of Solomon\n ▲ +175 Nana\n ▲ +203 Quo Vadis\n ▲ +33 Main Street\n ▲ +53 Matilda\n ▼ -215 Lolita\n ▼ -133 Paper Towns\n ▼ -193 Sounder\n ▼ -130 Are You There God? It's Me, Margaret\n ▼ -37 The Notebook\n ▼ -127 From the Mixed-Up Files of Mrs. Basil E. Frankweiler\n ▼ -93 Atlas Shrugged\n ▼ -53 The Fountainhead\n ▼ -110 Number the Stars\n ▼ -1 The Firm\n ▲ +92 Swann's Way\n ▼ -92 Ender's Game\n ▲ +102 The Name of the Rose\n ▼ -58 A Time to Kill\n ▼ -102 Water for Elephants\n ▲ +161 The Time Machine\n ▼ -130 Eragon\n ▼ -30 The Hitchhiker's Guide to the Galaxy\n ▲ +115 Buddenbrooks\n ▼ -29 A Thousand Splendid Suns\n ▼ -125 The Witch of Blackbird Pond\n ▼ -38 And Then There Were None\n ▼ -89 A Separate Peace\n ▼ -98 Breaking Dawn\n ▲ +40 As I Lay Dying\n ▼ -52 The Girl Who Played With Fire\n ▼ -178 Where the Red Fern Grows\n ▲ +57 Le Morte D'Arthur\n ▼ -112 Mockingjay\n ▲ +37 The Pillars of the Earth\n ▲ +154 Persian Letters\n ▼ -22 The Client\n ▼ -4 Sula\n ▼ -136 Tales of a Fourth Grade Nothing\n ▲ +13 The Merry Adventures of Robin Hood of Great Renown In Nottinghamshire\n ▲ +37 Tortilla Flat\n ▲ +2 Look Homeward, Angel\n ▲ +180 The Mystery of Edwin Drood\n ▼ -5 Brideshead Revisited\n ▼ -1 The Pelican Brief\n ▼ -21 Atonement\n ▲ +119 Washington Square\n ▼ -191 Like Water for Chocolate\n ▼ -171 The Golden Compass\n ▼ -106 The Secret Life of Bees\n ▼ -28 The Fault In Our Stars\n ▲ +145 Nostromo\n ▲ +78 Finnegans Wake\n ▲ +4 The Brethren\n ▲ +12 Coraline\n ▲ +208 Heart of Darkness\n ▼ -104 On the Banks of Plum Creek\n ▼ -32 Rebecca of Sunnybrook Farm\n ▲ +111 The Ambassadors\n ▲ +177 The Secret Agent\n ▼ -94 The House on Mango Street\n ▲ +38 Go Tell It on the Mountain\n ▲ +25 The Testament\n ▼ -80 The Clan of the Cave Bear\n ▲ +187 Cranford\n ▼ -100 Because of Winn-Dixie\n ▼ -127 My Side of the Mountain\n ▼ -48 The Runaway Jury\n ▼ -121 The Mouse and the Motorcycle\n ▼ -31 The Lost Symbol\n ▲ +128 The Forsyte Saga\n ▼ -39 Gone Girl\n ▼ -33 The Lightning Thief\n ▲ +201 The Last Days of Pompeii\n ▲ +44 The Reader\n ▼ -78 Caddie Woodlawn\n ▼ -120 The Tale of Despereaux\n ▼ -10 The Girl Who Kicked the Hornet's Nest\n ▼ -109 Dear Mr. Henshaw\n ▼ -90 The Killer Angels\n ▲ +140 Chronicle of a Death Foretold\n ▼ -86 The Five People You Meet In Heaven\n ▲ +186 The Master and Margarita\n ▲ +93 Winesburg, Ohio\n ▼ -138 P Is for Peril\n ▼ -57 My Sister's Keeper\n ▲ +261 Barnaby Rudge\n ▲ +150 Howards End\n ▲ +4 The Broker\n ▼ -77 The Camel Club\n ▲ +131 The Rainbow\n ▲ +92 The Man In the Iron Mask\n ▲ +15 Mary Poppins\n ▲ +20 Artemis Fowl\n ▼ -50 Dear John\n ▼ -12 Cold Mountain\n ▼ -62 Flowers for Algernon\n ▼ -32 The Dark Is Rising\n ▲ +204 Resurrection\n ▼ -134 Fearless Fourteen\n ▲ +266 A Sentimental Journey Through France and Italy\n ▲ +15 The King of Torts\n ▼ -103 The Graveyard Book\n ▲ +145 The Quiet American\n ▲ +47 The Chamber\n ▲ +97 The English Patient\n ▼ -22 Snow Falling on Cedars\n ▼ -73 The Long Winter\n ▼ -84 Sarah, Plain and Tall\n ▼ -119 Cross Country\n ▲ +124 The Spy Who Came In from the Cold\n ▲ +28 A Game of Thrones\n ▲ +132 The Thorn Birds\n ▼ -66 Old Yeller\n ▼ -80 Ramona Quimby, Age 8\n ▲ +206 Death In Venice\n ▼ -54 By the Shores of Silver Lake\n ▲ +73 Inferno\n ▲ +86 Schindler's List\n ▼ -28 Jonathan Livingston Seagull\n ▼ -14 The Stand\n ▼ -47 The Last Juror\n ▼ -96 Shiloh\n ▲ +52 Girl With a Pearl Earring\n ▲ +152 The Murder of Roger Ackroyd\n ▲ +87 It\n ▲ +67 The Rainmaker\n ▼ -48 The Poisonwood Bible\n ▼ -28 The Indian in the Cupboard\n ▲ +136 The Maltese Falcon\n ▲ +196 The Warden\n ▲ +39 The Summons\n ▼ -85 Encyclopedia Brown: Boy Detective\n ▲ +31 The Time Traveler's Wife\n ▲ +78 The Incredible Journey\n ▲ +68 Daughter of Fortune\n ▲ +243 Shirley\n ▼ -89 Bud, Not Buddy\n ▲ +25 The Horse Whisperer\n ▲ +85 The Street Lawyer\n ▲ +230 Nausea\n ▲ +153 To Have and Have Not\n ▼ -7 The Bridges of Madison County\n ▲ +151 Anne of the Island\n ▲ +14 The Winter of Our Discontent\n ▲ +161 The Shining\n ▲ +214 The Tenant of Wildfell Hall\n ▼ -85 First Family\n ▲ +69 The Partner\n ▲ +68 The Girl on the Train\n ▲ +251 The Black Arrow: A Tale of the Two Roses\n ▼ -24 The Choice\n ▲ +113 The Virginian: A Horseman of the Plains\n ▼ -52 A Walk to Remember\n ▼ -35 The Maze Runner\n ▼ -56 The Westing Game\n ▼ -6 Misty of Chincoteague\n ▼ -41 Diary of a Wimpy Kid: The Last Straw\n ▲ +211 King Solomon's Mines\n ▼ -54 Jacob Have I Loved\n ▼ -24 Mrs. Frisby and the Rats of NIMH\n ▲ +156 Misery\n ▲ +42 The Cider House Rules\n ▼ -13 King of the Wind\n ▲ +63 The Once and Future King\n ▲ +92 The Witches\n ▲ +51 The Subtle Knife\n ▼ -61 When You Reach Me\n ▲ +161 Carrie\n ▲ +236 The Moon and Sixpence\n ▼ -67 The Higher Power of Lucky\n ▲ +213 Looking Backward, 2000-1887\n ▲ +178 The Wings of the Dove\n ▼ -50 The Summer of the Swans\n ▲ +151 Dangerous Liaisons\n ▲ +83 Jurassic Park\n ▼ -17 The Absolutely True Diary of a Part-time Indian\n ▼ -35 The Grey King\n ▲ +280 The Leopard\n ▲ +35 The Mammoth Hunters\n ▼ -26 The Trumpet of the Swan\n ▲ +19 The Lucky One\n ▲ +3 These Happy Golden Years\n ▲ +180 Arrowsmith\n ▼ -18 Julie of the Wolves\n ▲ +16 The Screwtape Letters\n ▲ +379 The Fall\n ▲ +12 The No. 1 Ladies' Detective Agency\n ▼ -44 Worst Case\n ▲ +169 Lost Horizon\n ▲ +59 The Gunslinger\n ▼ -18 The Slave Dancer\n ▼ -42 Harry Potter and the Half-Blood Prince\n ▲ +76 Inkheart\n ▼ -17 Ramona and her Father\n ▼ -6 Inkspell\n ▼ -4 Ramona the Pest\n ▲ +14 Walk Two Moons\n ▼ -35 Miss Peregrine's Home for Peculiar Children\n ▲ +42 The Chocolate War\n ▲ +114 Sophie's Choice\n ▲ +97 Looking for Alaska\n ▲ +236 Breakfast at Tiffany's\n ▲ +193 The Razor's Edge\n ▲ +9 Dreamcatcher\n ▲ +300 Orlando\n ▲ +20 The Things they Carried\n ▲ +25 Little Town on the Prairie\n ▲ +19 Nights in Rodanthe\n ▲ +102 The Amber Spyglass\n ▼ -12 The Miraculous Journey of Edward Tulane\n ▲ +234 Flatland\n ▼ -2 Diary of a Wimpy Kid\n ▲ +14 The Memory Keeper's Daughter\n ▲ +18 The Wedding\n ▲ +55 Fried Green Tomatoes at the Whistle-Stop Cafe\n ▲ +61 The Cricket in Times Square\n ▲ +84 The Phantom Tollbooth\n ▲ +350 Rob Roy\n ▲ +257 The Death of Ivan Ilych\n ▼ -15 Alex Cross's Trial\n ▲ +463 Kenilworth\n ▲ +389 The Life and Opinions of Tristram Shandy\n ▼ -1 M.C. Higgins, The Great\n ▲ +17 Call It Courage\n ▲ +21 Go Set a Watchman\n ▲ +81 Bleachers\n ▼ -10 Elijah of Buxton\n ▲ +2 Swimsuit\n ▲ +164 Cat's Cradle\n ▲ +159 The Caine Mutiny\n ▲ +236 The Heart of the Matter\n ▲ +52 Harriet, the Spy\n ▲ +271 Darkness at Noon\n ▲ +112 A Prayer for Owen Meany\n ▲ +143 The God of Small Things\n ▲ +87 The Associate\n ▲ +67 The Shack\n ▲ +240 The Naked and the Dead\n ▲ +60 The Sea of Monsters\n ▲ +146 Stranger in a Strange Land\n ▲ +23 Vision in White\n ▲ +22 The Whipping Boy\n ▲ +110 Room\n ▲ +127 Deception Point\n                                title                  author  top_500_rank  \\\n0                         Don Quixote     Miguel de Cervantes             1   \n1    Alice's Adventures in Wonderland           Lewis Carroll             2   \n2  The Adventures of Huckleberry Finn              Mark Twain             3   \n3        The Adventures of Tom Sawyer              Mark Twain             4   \n4                     Treasure Island  Robert Louis Stevenson             5   \n\n   oclc_editions_rank  \n0                 1.0  \n1                33.0  \n2                 6.0  \n3                 7.0  \n4                 2.0  \n                  title                  author  top_500_rank  \\\n0           Don Quixote     Miguel de Cervantes             1   \n4       Treasure Island  Robert Louis Stevenson             5   \n5   Pride and Prejudice             Jane Austen             6   \n88           Persuasion             Jane Austen            89   \n7             Jane Eyre        Charlotte Brontë             8   \n\n    oclc_editions_rank  \n0                  1.0  \n4                  2.0  \n5                  3.0  \n88                 4.0  \n7                  5.0  \n ▼ -8 Don Quixote\n ▼ -16 Alice's Adventures in Wonderland\n ▼ -3 The Adventures of Huckleberry Finn\n ▼ -3 The Adventures of Tom Sawyer\n ▲ +4 Treasure Island\n ▲ +4 Pride and Prejudice\n ▲ +2 Wuthering Heights\n ▲ +4 Jane Eyre\n ▲ +1 Moby Dick\n ▼ -4 The Scarlet Letter\n ▼ -14 Gulliver's Travels\n ▼ -16 The Pilgrim's Progress\n ▼ -3 A Christmas Carol\n ▲ +3 David Copperfield\n ▲ +3 A Tale of Two Cities\n ▲ +6 Little Women\n ▲ +4 Great Expectations\n ▼ -17 The Hobbit, or, There and Back Again\n ▲ +4 Frankenstein, or, the Modern Prometheus\n ▲ +3 Oliver Twist\n ● 0 Uncle Tom's Cabin\n ▼ -43 Crime and Punishment\n ▼ -16 Madame Bovary: Patterns of Provincial life\n ▼ -438 The Return of the King\n ▼ -2 Dracula\n ▲ +6 The Three Musketeers\n ▼ -58 Brave New World\n ▼ -116 War and Peace\n ▲ +3 To Kill a Mockingbird\n ▼ -160 The Wizard of Oz\n ▲ +9 Les Misérables\n ▼ -27 The Secret Garden\n ▲ +4 Animal Farm\n ▲ +11 The Great Gatsby\n ▼ -32 The Little Prince\n ▼ -8 The Call of the Wild\n ▲ +1 20,000 Leagues Under the Sea\n ▲ +14 Anna Karenina\n ▼ -14 The Wind in the Willows\n ▼ -2 The Picture of Dorian Gray\n ▲ +9 The Grapes of Wrath\n ▼ -5 Sense and Sensibility\n ▼ -44 The Last of the Mohicans\n ▲ +6 Tess of the d'Urbervilles\n ▲ +15 Harry Potter and the Sorcerer's Stone\n ▼ -17 Heidi\n ▼ -2 Ulysses\n ▼ -424 The Complete Sherlock Holmes\n ▼ -7 The Count of Monte Cristo\n ▼ -2 The Old Man and the Sea\n ● 0 The Lion, the Witch, and the Wardrobe\n ▲ +21 The Hunchback of Notre Dame\n ▼ -416 Pinocchio\n ▼ -147 One Hundred Years of Solitude\n ▲ +15 Ivanhoe\n ▼ -30 The Red Badge of Courage\n ▲ +7 Anne of Green Gables\n ▼ -44 Black Beauty\n ▼ -97 Peter Pan\n ▲ +6 A Farewell to Arms\n ▼ -27 The House of the Seven Gables\n ▲ +4 Lord of the Flies\n ▼ -11 The Prince and the Pauper\n ▼ -7 A Portrait of the Artist as a Young Man\n ▼ -12 Lord Jim\n ▲ +23 Harry Potter and the Chamber of Secrets\n ▲ +8 The Stranger\n ● 0 The Trial\n ▼ -34 Lady Chatterley's Lover\n ▼ -423 Kidnapped: The Adventures of David Balfour\n ▼ -9 The Catcher in the Rye\n ▼ -10 Fahrenheit 451\n ▼ -24 A Journey to the Center of the Earth\n ▼ -4 Vanity Fair\n ▲ +10 All Quiet on the Western Front\n ▼ -24 Gone with the Wind\n ▼ -2 My Ántonia\n ▲ +46 Of Mice and Men\n ▲ +12 The Vicar of Wakefield\n ▲ +6 A Connecticut Yankee in King Arthur's Court\n ▲ +37 White Fang\n ▼ -29 Fathers and Sons\n ▼ -181 Doctor Zhivago\n ▲ +13 The Decameron\n ▲ +24 Nineteen Eighty-Four\n ▼ -16 The Jungle\n ▼ -12 The Da Vinci Code\n ▲ +86 Persuasion\n ▲ +8 Mansfield Park\n ▲ +43 Candide\n ▲ +3 For Whom the Bell Tolls\n ▼ -13 Far from the Madding Crowd\n ▼ -77 The Fellowship of the Ring\n ▼ -2 The Return of the Native\n ▼ -9 Sons and Lovers\n ▲ +2 Charlotte's Web\n ▼ -15 The Swiss Family Robinson\n ▲ +5 Bleak House\n ▲ +10 Père Goriot\n ▲ +8 Utopia\n ▲ +24 The History of Tom Jones, a Foundling\n ▲ +46 Harry Potter and the Prisoner of Azkaban\n ▼ -4 Kim\n ▼ -103 The Sound and the Fury\n ▲ +33 Harry Potter and the Goblet of Fire\n ● 0 The Mill on the Floss\n ▲ +44 A Wrinkle in Time\n ▼ -6 The Hound of the Baskervilles\n ▼ -115 The Two Towers\n ▼ -11 The War of the Worlds\n ▲ +3 Middlemarch\n ▼ -6 The Age of Innocence\n ● 0 The Color Purple\n ▼ -13 Northanger Abbey\n ▼ -29 East of Eden\n ▼ -59 On the Road\n ▼ -3 Catch-22\n ▲ +82 Around the World in Eighty Days\n ▼ -3 Hard Times\n ▲ +10 Beloved\n ▲ +6 Mrs. Dalloway\n ▼ -3 To the Lighthouse\n ▼ -6 The Magician's Nephew\n ▲ +29 Harry Potter and the Order of the Phoenix\n ▲ +71 The Sun Also Rises\n ▼ -4 The Good Earth\n ▲ +52 Silas Marner\n ▲ +4 Love in the Time of Cholera\n ▼ -7 Rebecca\n ▼ -3 Jude the Obscure\n ▼ -62 Twilight\n ● 0 A Passage to India\n ▲ +17 The Plague\n ▼ -342 Nicholas Nickleby\n ▲ +102 The Pearl\n ▼ -6 Ethan Frome\n ▲ +11 The Tale of Genji\n ▲ +21 The Giver\n ▼ -2 The Alchemist\n ▼ -61 The Strange Case of Dr. Jekyll and Mr. Hyde\n ▼ -39 Robinson Crusoe\n ▼ -6 Tender is the Night\n ▼ -45 The Idiot\n ▲ +4 Hatchet\n ▼ -16 The Kite Runner\n ▲ +11 One Flew Over the Cuckoo's Nest\n ▲ +38 The Portrait of a Lady\n ▲ +14 The Outsiders\n ▼ -8 Ben-Hur\n ▼ -53 The Mayor of Casterbridge\n ● 0 Cry, The Beloved Country\n ▼ -24 The Last Battle\n ▼ -25 Captains Courageous\n ▲ +7 The Castle\n ▲ +86 The Metamorphosis\n ▲ +37 The Magic Mountain (Der Zauberberg)\n ▲ +12 James and the Giant Peach\n ▼ -1 The Horse and His Boy\n ▲ +4 The Voyage of the Dawn Treader\n ▲ +15 The Bell Jar\n ▼ -5 Women in Love\n ▲ +3 The Yearling\n ▲ +11 O Pioneers!\n ▲ +74 The Handmaid's Tale\n ▲ +3 The Moonstone\n ▲ +13 The Old Curiosity Shop\n ▼ -6 Little Dorrit\n ▼ -36 Prince Caspian: The Return to Narnia\n ▲ +8 Sister Carrie\n ▲ +7 The Silver Chair\n ▲ +7 The Hunger Games\n ▲ +1 This Side of Paradise\n ▲ +84 Eugénie Grandet\n ▼ -2 Of Human Bondage\n ▼ -274 Dream of the Red Chamber\n ▼ -6 Life of Pi\n ▲ +47 Harry Potter and the Deathly Hallows\n ▲ +29 Invisible Man\n ▲ +9 Steppenwolf\n ▲ +98 The Sorrows of Young Werther\n ▲ +33 Bridge to Terabithia\n ▲ +46 The Invisible Man\n ▲ +32 Holes\n ▲ +57 Siddhartha\n ▼ -10 A Tree Grows in Brooklyn\n ▲ +169 Through the Looking-Glass, and What Alice Found There\n ▼ -4 In Cold Blood\n ▲ +7 The House of the Spirits\n ▲ +9 Adam Bede\n ▼ -37 The Betrothed\n ▼ -7 The Book Thief\n ▲ +35 Their Eyes Were Watching God\n ▼ -18 One Day in the Life of Ivan Denisovich\n ▲ +150 The Sea Wolf\n ▲ +30 Catching Fire\n ▲ +6 Roll of Thunder, Hear My Cry\n ▲ +8 Death Comes for the Archbishop\n ▲ +12 The House of Mirth\n ▲ +16 Light in August\n ▼ -268 The Pickwick Papers\n ▲ +23 Remembrance of Things Past\n ▼ -291 Barchester Towers and the Warden\n ▼ -4 The Bridge of San Luis Rey\n ▼ -5 The Help\n ▲ +12 Murder on the Orient Express\n ▼ -46 The Lovely Bones\n ▼ -181 The Appeal\n ▲ +14 Dombey And Son\n ▼ -253 Slaughterhouse-Five\n ▲ +7 An American Tragedy\n ▲ +43 The Bluest Eye\n ▲ +16 Little House In the Big Woods\n ▼ -1 Pippi Longstocking\n ▲ +13 Germinal\n ▼ -1 The Heart Is a Lonely Hunter\n ▼ -10 The Woman In White\n ▼ -227 Absalom, Absalom!\n ▼ -114 A Painted House\n ● 0 The Girl With the Dragon Tattoo\n ▼ -42 A Room With a View\n ▲ +9 Watership Down\n ▼ -22 Memoirs of a Geisha\n ▲ +10 Our Mutual Friend\n ▲ +3 Babbitt\n ▲ +87 The Red Pony\n ▲ +59 All the King's Men\n ▲ +19 Things Fall Apart\n ▼ -3 Lorna Doone\n ▲ +7 Johnny Tremain\n ▲ +1 Anne of Avonlea\n ▲ +11 Tuck Everlasting\n ▼ -9 The BFG\n ▼ -14 Cannery Row\n ▼ -17 The Joy Luck Club\n ▲ +25 The Silmarillion\n ▼ -10 Roots\n ▲ +40 Little House on the Prairie\n ▲ +21 Native Son\n ▲ +15 Stuart Little\n ▼ -246 Cross Fire\n ▲ +8 The Power and the Glory\n ▲ +6 A Clockwork Orange\n ▲ +6 The Phantom of the Opera\n ▼ -15 The Martian Chronicles\n ▲ +11 The Road\n ▲ +11 The Way of All Flesh\n ▼ -219 Diary of a Wimpy Kid: The Long Haul\n ▲ +23 Villette\n ▼ -23 The Curious Incident of the Dog In the Night-Time\n ▲ +153 The Mysterious Island\n ▲ +21 Song of Solomon\n ▲ +10 Nana\n ▼ -48 Quo Vadis\n ● 0 Main Street\n ▲ +83 Matilda\n ▼ -225 Lolita\n ▼ -68 Paper Towns\n ▲ +8 Sounder\n ▲ +1 Are You There God? It's Me, Margaret\n ▲ +5 The Notebook\n ▲ +21 From the Mixed-Up Files of Mrs. Basil E. Frankweiler\n ▲ +17 Atlas Shrugged\n ▲ +14 The Fountainhead\n ▲ +36 Number the Stars\n ▼ -75 The Firm\n ▲ +2 Swann's Way\n ▲ +28 Ender's Game\n ▲ +36 The Name of the Rose\n ▼ -40 A Time to Kill\n ▼ -10 Water for Elephants\n ▲ +134 The Time Machine\n ▼ -134 Eragon\n ▼ -62 The Hitchhiker's Guide to the Galaxy\n ▼ -180 Buddenbrooks\n ▲ +9 A Thousand Splendid Suns\n ▲ +6 The Witch of Blackbird Pond\n ▼ -84 And Then There Were None\n ▲ +11 A Separate Peace\n ▼ -11 Breaking Dawn\n ▲ +75 As I Lay Dying\n ▼ -2 The Girl Who Played With Fire\n ▼ -5 Where the Red Fern Grows\n ▼ -36 Le Morte D'Arthur\n ▲ +46 Mockingjay\n ▲ +8 The Pillars of the Earth\n ▼ -25 Persian Letters\n ▼ -46 The Client\n ▲ +27 Sula\n ▲ +14 Tales of a Fourth Grade Nothing\n ▼ -97 The Merry Adventures of Robin Hood of Great Renown In Nottinghamshire\n ▲ +43 Tortilla Flat\n ▲ +19 Look Homeward, Angel\n ▼ -17 The Mystery of Edwin Drood\n ▼ -135 Brideshead Revisited\n ▼ -79 The Pelican Brief\n ▲ +3 Atonement\n ▲ +18 Washington Square\n ▼ -184 Like Water for Chocolate\n ▼ -55 The Golden Compass\n ▲ +15 The Secret Life of Bees\n ▲ +41 The Fault In Our Stars\n ▲ +31 Nostromo\n ▲ +35 Finnegans Wake\n ▲ +6 The Brethren\n ▲ +40 Coraline\n ▲ +88 Heart of Darkness\n ▲ +18 On the Banks of Plum Creek\n ▼ -35 Rebecca of Sunnybrook Farm\n ▲ +25 The Ambassadors\n ▲ +19 The Secret Agent\n ▼ -101 The House on Mango Street\n ▲ +43 Go Tell It on the Mountain\n ▼ -4 The Testament\n ▼ -52 The Clan of the Cave Bear\n ▲ +34 Cranford\n ▲ +73 Because of Winn-Dixie\n ▲ +18 My Side of the Mountain\n ▼ -89 The Runaway Jury\n ▼ -4 The Mouse and the Motorcycle\n ▲ +23 The Lost Symbol\n ▲ +26 The Forsyte Saga\n ▲ +17 Gone Girl\n ▲ +70 The Lightning Thief\n ▼ -58 The Last Days of Pompeii\n ▲ +19 The Reader\n ▲ +23 Caddie Woodlawn\n ▲ +41 The Tale of Despereaux\n ▼ -20 The Girl Who Kicked the Hornet's Nest\n ▲ +15 Dear Mr. Henshaw\n ▲ +17 The Killer Angels\n ▲ +35 Chronicle of a Death Foretold\n ▲ +24 The Five People You Meet In Heaven\n ▲ +29 The Master and Margarita\n ▼ -107 Winesburg, Ohio\n ▼ -136 P Is for Peril\n ▲ +6 My Sister's Keeper\n ▲ +215 Barnaby Rudge\n ▲ +82 Howards End\n ▲ +32 The Broker\n ▼ -133 The Camel Club\n ▲ +19 The Rainbow\n ▼ -48 The Man In the Iron Mask\n ▼ -120 Mary Poppins\n ▲ +62 Artemis Fowl\n ▲ +8 Dear John\n ▲ +8 Cold Mountain\n ▲ +1 Flowers for Algernon\n ▼ -1 The Dark Is Rising\n ▼ -116 Resurrection\n ▼ -128 Fearless Fourteen\n ▲ +167 A Sentimental Journey Through France and Italy\n ▲ +24 The King of Torts\n ▲ +96 The Graveyard Book\n ▲ +28 The Quiet American\n ▼ -5 The Chamber\n ▼ -1 The English Patient\n ▼ -65 Snow Falling on Cedars\n ▲ +42 The Long Winter\n ▲ +85 Sarah, Plain and Tall\n ▼ -120 Cross Country\n ▼ -15 The Spy Who Came In from the Cold\n ▼ -32 A Game of Thrones\n ▼ -7 The Thorn Birds\n ▲ +52 Old Yeller\n ▲ +63 Ramona Quimby, Age 8\n ▼ -110 Death In Venice\n ▲ +52 By the Shores of Silver Lake\n ▲ +23 Inferno\n ▲ +75 Schindler's List\n ▼ -107 Jonathan Livingston Seagull\n ▼ -118 The Stand\n ▼ -44 The Last Juror\n ▲ +55 Shiloh\n ▲ +7 Girl With a Pearl Earring\n ▲ +11 The Murder of Roger Ackroyd\n ▲ +84 It\n ▲ +43 The Rainmaker\n ▲ +47 The Poisonwood Bible\n ▲ +16 The Indian in the Cupboard\n ▼ -62 The Maltese Falcon\n ▲ +45 The Warden\n ▲ +31 The Summons\n ▼ -107 Encyclopedia Brown: Boy Detective\n ▼ -9 The Time Traveler's Wife\n ▲ +27 The Incredible Journey\n ▲ +33 Daughter of Fortune\n ▲ +63 Shirley\n ▲ +7 Bud, Not Buddy\n ▼ -72 The Horse Whisperer\n ▲ +22 The Street Lawyer\n ▲ +70 Nausea\n ▼ -5 To Have and Have Not\n ▼ -64 The Bridges of Madison County\n ▲ +17 Anne of the Island\n ▲ +53 The Winter of Our Discontent\n ▲ +69 The Shining\n ▼ -3 The Tenant of Wildfell Hall\n ▼ -90 First Family\n ▼ -19 The Partner\n ▲ +124 The Girl on the Train\n ▲ +28 The Black Arrow: A Tale of the Two Roses\n ▲ +8 The Choice\n ▲ +15 The Virginian: A Horseman of the Plains\n ▼ -46 A Walk to Remember\n ▲ +67 The Maze Runner\n ▲ +66 The Westing Game\n ▲ +23 Misty of Chincoteague\n ▲ +121 Diary of a Wimpy Kid: The Last Straw\n ▼ -30 King Solomon's Mines\n ▲ +11 Jacob Have I Loved\n ▲ +84 Mrs. Frisby and the Rats of NIMH\n ▲ +31 Misery\n ▼ -24 The Cider House Rules\n ▲ +41 King of the Wind\n ▲ +31 The Once and Future King\n ▲ +56 The Witches\n ▲ +48 The Subtle Knife\n ▲ +73 When You Reach Me\n ▲ +19 Carrie\n ▲ +13 The Moon and Sixpence\n ▲ +51 The Higher Power of Lucky\n ▲ +68 Looking Backward, 2000-1887\n ▲ +125 The Wings of the Dove\n ▼ -24 The Summer of the Swans\n ▼ -64 Dangerous Liaisons\n ▲ +14 Jurassic Park\n ▲ +85 The Absolutely True Diary of a Part-time Indian\n ▼ -1 The Grey King\n ▲ +62 The Leopard\n ▼ -14 The Mammoth Hunters\n ▲ +49 The Trumpet of the Swan\n ▲ +38 The Lucky One\n ▲ +56 These Happy Golden Years\n ▲ +56 Arrowsmith\n ▲ +59 Julie of the Wolves\n ▲ +23 The Screwtape Letters\n ▲ +380 The Fall\n ▲ +7 The No. 1 Ladies' Detective Agency\n ▼ -43 Worst Case\n ▲ +21 Lost Horizon\n ▲ +17 The Gunslinger\n ▲ +14 The Slave Dancer\n ▲ +34 Harry Potter and the Half-Blood Prince\n ▲ +21 Inkheart\n ▲ +56 Ramona and her Father\n ▲ +45 Inkspell\n ▲ +50 Ramona the Pest\n ▲ +85 Walk Two Moons\n ▼ -28 Miss Peregrine's Home for Peculiar Children\n ▲ +28 The Chocolate War\n ▲ +18 Sophie's Choice\n ▲ +95 Looking for Alaska\n ▲ +38 Breakfast at Tiffany's\n ▲ +18 The Razor's Edge\n ▼ -17 Dreamcatcher\n ▲ +180 Orlando\n ▲ +104 The Things they Carried\n ▲ +110 Little Town on the Prairie\n ▲ +3 Nights in Rodanthe\n ▲ +70 The Amber Spyglass\n ▲ +111 The Miraculous Journey of Edward Tulane\n ▲ +36 Flatland\n ▲ +250 Diary of a Wimpy Kid\n ▼ -3 The Memory Keeper's Daughter\n ▲ +35 The Wedding\n ▲ +31 Fried Green Tomatoes at the Whistle-Stop Cafe\n ▲ +17 The Cricket in Times Square\n ▲ +62 The Phantom Tollbooth\n ▲ +73 Rob Roy\n ▲ +8 The Death of Ivan Ilych\n ▼ -14 Alex Cross's Trial\n ▲ +435 Kenilworth\n ▲ +290 The Life and Opinions of Tristram Shandy\n ▲ +30 M.C. Higgins, The Great\n ▲ +51 Call It Courage\n ▲ +159 Go Set a Watchman\n ▲ +25 Bleachers\n ▲ +77 Elijah of Buxton\n ▼ -1 Swimsuit\n ▲ +63 Cat's Cradle\n ▲ +50 The Caine Mutiny\n ▲ +26 The Heart of the Matter\n ▲ +63 Harriet, the Spy\n ▲ +51 Darkness at Noon\n ▲ +78 A Prayer for Owen Meany\n ▲ +36 The God of Small Things\n ▲ +47 The Associate\n ▲ +78 The Shack\n ▲ +44 The Naked and the Dead\n ▲ +88 The Sea of Monsters\n ▲ +75 Stranger in a Strange Land\n ▲ +10 Vision in White\n ▲ +51 The Whipping Boy\n ▲ +41 Room\n ▲ +26 Deception Point\n                                title                  author  top_500_rank  \\\n0                         Don Quixote     Miguel de Cervantes             1   \n1    Alice's Adventures in Wonderland           Lewis Carroll             2   \n2  The Adventures of Huckleberry Finn              Mark Twain             3   \n3        The Adventures of Tom Sawyer              Mark Twain             4   \n4                     Treasure Island  Robert Louis Stevenson             5   \n\n   oclc_holdings_rank  \n0                 9.0  \n1                18.0  \n2                 6.0  \n3                 7.0  \n4                 1.0  \n                  title                  author  top_500_rank  \\\n4       Treasure Island  Robert Louis Stevenson             5   \n5   Pride and Prejudice             Jane Austen             6   \n88           Persuasion             Jane Austen            89   \n7             Jane Eyre        Charlotte Brontë             8   \n6     Wuthering Heights            Emily Brontë             7   \n\n    oclc_holdings_rank  \n4                  1.0  \n5                  2.0  \n88                 3.0  \n7                  4.0  \n6                  5.0  \n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=11}\n```\n4.9\n```\n:::\n:::\n\n\nComparing the average points of movement between the top 500 and 3 other ranking lists, we can see that the novels moved the least when compared to the number of holdings ranking (45 pts). Novels were 2x more likely to move positions when compared to the number of editions ranking (82 pts) and 3x more likely to move when compared to GoodReads rankings (137 pts).\n\n<TODO: how to show significant relationship between num holdings, top 500 and num holdings, num editions, but NOT goodreads?>\n\nWithin the top 10 rankings specifically, only 2 books were not the same when compared to number of holdings, 4 books were not the same when compared to editions rankings, and 9 books were not the same when compared to GoodReads rankings.\n\n## **FULL-TEXT ANALYSIS**\n\nNow we can look at the `final_merged_dataset.tsv` file, which also includes the full-text of all the novels on the list that are in the public domain. We will be working with the  `full_text` column, which is a cleaned version of each book.\n\n::: {.cell execution_count=12}\n``` {.python .cell-code}\nimport pandas as pd\nimport requests\nimport re\nfrom bs4 import BeautifulSoup\nimport random\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n/Users/melwalsh/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning:\n\nurllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020\n\n```\n:::\n:::\n\n\nLet's start by analyzing the type-token ratio of our texts by genre. The type-token ratio will tell us which genres contain the most unique words.\n\nThe type-token ratio is a simple expression that calculates # of unique words / total words in a selection. As you may be able to surmise, sometimes this ratio is naturally higher for shorter books. To avoid this bias, we randomly select a contiguous 1000 word sample from each book and average the scores across genres.\n\nIt's helpful to be able to store all of our data in a dataframe, but sometimes we want to work with just one column of the data and converting it into a different datatype can be helpful. Here we're converting all the information in the column \"text\" into a list.\n\n::: {.cell execution_count=13}\n``` {.python .cell-code}\ndef get_ttr(text):\n  if (pd.isnull(text)):\n    return 1.1 # a ratio greater than 1 is impossible, so we won't count these when doing our averages\n  else:\n    text = text.lower()\n    punctuations = \"-,.?!;#: \\n\\t\"\n    no_punct = text.strip(punctuations)\n    tokens = text.split()\n\n    trial = 0\n    avg_ttr = 0\n    while (trial < 10):\n      random_token_num = random.randrange(0, len(tokens)-1000)\n      sample = tokens[random_token_num:(random_token_num+1000)]\n      trial += 1\n      avg_ttr += float(len(set(sample)))/1000\n\n    return avg_ttr/10\n\n    import csv\n\ndf = pd.read_csv(\"final_merged_dataset.tsv\", sep='\\t', header=0, low_memory=False)\ndf[\"ttr\"] = df[\"full_text\"].apply(get_ttr)\n\ncleaned = df[df[\"ttr\"] <= 1] # drop all rows where ttr is not applicable\ngrouped = cleaned.groupby('genre')\navg_ttr = grouped[\"ttr\"].mean().sort_values(ascending=False)\nprint(avg_ttr)\n\nsorted = cleaned.sort_values(by=['ttr'], ascending=False)\nprint(sorted[[\"title\", \"author\", \"ttr\", \"genre\"]].head(10).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ngenre\npolitical     0.512486\nhistory       0.505636\nbildung       0.500900\nscifi         0.495940\nna            0.495334\nromance       0.491408\nmystery       0.490875\nautobio       0.490000\naction        0.484490\nfantasy       0.483229\nhorror        0.482750\nallegories    0.465867\nName: ttr, dtype: float64\n                                     title              author    ttr   genre\n                                   Ulysses         James Joyce 0.5480      na\n                         Wuthering Heights        Emily Brontë 0.5475      na\n                       Captains Courageous     Rudyard Kipling 0.5472 bildung\n                     This Side of Paradise F. Scott Fitzgerald 0.5468 bildung\n                                 Moby Dick     Herman Melville 0.5425      na\n                                  Villette    Charlotte Brontë 0.5392      na\n                                   Shirley    Charlotte Brontë 0.5387 history\n                                   Babbitt      Sinclair Lewis 0.5371      na\nMadame Bovary: Patterns of Provincial life    Gustave Flaubert 0.5366      na\n                                       Kim     Rudyard Kipling 0.5365  action\n```\n:::\n:::\n\n\n::: {.callout-tip}\n## Activity 1\n\n    &lt;**Activity** looking into the original languages of novels in the dataset?> For more, see [Activity 1](#exercise-1).\n:::\n\n\n## **CONCLUSION**\n\n\n\n# Explore the Data {#tabset-1-2}\n\n\n\n\n```{ojs}\n//| echo: false\n//| output: false\nlibrary_data = d3.csv(\"https://raw.githubusercontent.com/melaniewalsh/responsible-datasets-in-context/main/datasets/top-500-novels/library_top_500.csv\", d3.autoType)\n\nuse_data = d3.csv(\"https://raw.githubusercontent.com/melaniewalsh/responsible-datasets-in-context/main/datasets/national-parks/US-National-Parks_Use_1979-2023_By-Month.csv\", d3.autoType)\n```\n\n```{ojs}\n//| echo: false\n//| output: false\n\n\nfiltered = library_data.filter(function(penguin) {\n  return bill_length_min < penguin.bill_length_mm &&\n         islands.includes(penguin.island);\n})\n```\n\n```{ojs}\n//| echo: false\ncolor = d3\n  .scaleLinear()\n  .domain([0, 100, 300])\n  .range([\"#cafcc2\", \"#fce7c2\", \"#eb9494\"])\n```\n\n\n<br>\n\n## Library Top 500\n\n\n\n```{ojs}\n//| echo: false\nviewof search = Inputs.search(library_data, {\n  placeholder: \"Search\"\n})\n```\n\n\n\n<br>\n\n\n\n```{ojs}\n//| echo: false\n\n/*Inputs.table(search, data)*/\n\nInputs.table(search, {\n  layout: \"fixed\",\n  rows: 50,\n  sort: \"top_500_rank\",\n  reverse: false,\n  format: {\n    /*RecreationVisits: x => d3.format('.2s')(x),*/\n    pub_year: x => d3.timeFormat(x),\n    author_birth: x => d3.timeFormat(x),\n    author_death: x => d3.timeFormat(x),\n    gr_num_ratings_rank: x => html`<div style='background:${color(x)}'>${d3.format('.2s')(x)}</div>`\n  }\n})\n```\n\n{{< downloadthis ../../../datasets/top-500-novels/library_top_500.csv dname = library_top_500 label = \"Download Data\" id = downloadbutton >}}\n\n\n\n\n\n\n# Exercises {#exercises}\n\n::: {.panel-tabset .nav-pills}\n# R\n\n::: {#exercise-posts}\n:::\n\n# Python\n:::\n\n# Discussion & Activities {#discussion-and-activities}\n\n## Activity 1 {#exercise-1}\n\nIt is inevitable that the devices that the National Park Service uses to count visits to the parks — like induction loop counters installed on the road — will break. But they will also get *fixed* at different rates, in different locations, as we could see in the case of Crater Lake National Park (where a counter was fixed quickly) and Carlsbad Caverns National Park (where a broken counter from 2019 still has not been fixed).\n\nThere are many reasons for these disparities, but some of the big ones might be geography and resources. The more remote a park, the harder it is to get a repair team to it. The less-resourced a park, the lower the likelihood they have on-site repair teams, or are prioritized by the repair teams that can be dispatched.\n\nWith this in mind, look at the locations of the following parks. Suppose that each one has an outage in their induction loop counter: which ones would you expect to be fixed first, and why? Research the parks, and rank them on a scale of 1 to 5 (1 being highest, and 5 being lowest) of which would be fixed quickest.\n\n| Park               | Priority (1-5) | Reason |\n|--------------------|----------------|--------|\n| Acadia NP          |                |        |\n| Lassen Volcanic NP |                |        |\n| Saguaro NP         |                |        |\n| Yosemite NP        |                |        |\n| Mammoth Cave NP    |                |        |\n\n## Activity 2 {#exercise-2}\n\nThe National Park Service sometimes fills in missing data with hard numbers or approximates data by applying special mathematical formulas. This is necessary work, but it is also under-explained work.\n\nTo see this in action, go to [the NPS page that documents park reports](https://irma.nps.gov/Stats/Reports/Park) and down the \"Visitor Use Counting Procedures\" PDF for three different parks.\n\nHow are the procedures for these three parks similar or different? What kind of effect do you think this has on the resulting data? What do you think is the best of documenting this information and communicating it to users of the data?\n\n## Activity 3\n\nIn 2014 and 2015, Kobuk Valley National Park reported that there were zero visitors to the park.\n\nUse publicly available internet data - Twitter posts, Flickr photos, etc - to try and find evidence of people visiting the park (there is existing evidence!). \n\nBased on your findings, how do you think, differently, if at all, about Kobuk Valley's decision to record zero visits and about alternative methods for counting visits?\n\n:::\n\n",
    "supporting": [
      "top-500-novels_files/figure-pdf"
    ],
    "filters": []
  }
}