project:
  type: website
  # output-dir: ../docs

render:
  - team:
      output-dir: ../docs/team

website:
  image: images/responsible-logo.png
  twitter-card: true
  bread-crumbs: false
  title: "Responsible Datasets in Context"
  site-url: https://www.responsible-datasets-in-context.com
  favicon: images/responsible-logo-white.png
  google-analytics:  G-MZHBEJTWJ4
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
      showHighlights: whenSidebarOpen
  navbar:
    logo: images/responsible-logo-white.png
    right:
      - datasets.qmd
      - text: "Mission"
        href: mission.qmd
      - text: "Team"
        href: team.qmd
      - text: "About"
        menu: 
        - text: "Sponsors"
          href: sponsors.qmd
        - text: "Get In Touch"
          href: get-in-touch.qmd
      - icon: github
        href: https://github.com/melaniewalsh/responsible-datasets-in-context
  sidebar:
    - id: np-data
      # logo: images/responsible-logo.png
      # title: "NP Data"
      # subtitle: "NP Data"
      style: "docked"
      search: true
      background: "white"
      type: light
      border: true
      pinned: false
      # tools:
      # - icon: github
      #   href: https://github.com/sta210-s22
      #   text: "GitHub organization"
      # - icon: code-square
      #   href: https://cmgr.oit.duke.edu/containers
      #   text: "RStudio Containers"
      # - icon: person-fill
      #   text: "Sakai"
      #   menu:
      #     - text: Discussion forum
      #       url: https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/tool/13b6446a-a6c6-4222-8cfb-c36d1f70802b
      #     - text: Gradescope
      #       url: https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/page/aec742dc-2972-4f02-a35b-1dd3315af889
      #     - text: Gradebook
      #       url: https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/tool/69078433-67a6-4054-a2e7-9e6c202ecdc3/
      contents:
        - section: "Guide"
          contents:
            - text: "Data Essay"
              href: posts/np-data/data-essay.qmd
            - text: "Discussion Questions and Activities"
              href: posts/np-data/discussion-activities.qmd
            - text: "Programming Exercises"
              href: posts/np-data/programming-exercises.qmd

               
  page-footer:
    background: "#000000"
    right: <p style="color:white">Copyright &copy; 2024</p>
    left:   <p style="color:white">Supported by[![](https://assets.mofoprod.net/network/images/mo-fo_logo-w.2e16d0ba.fill-890x890-c100.format-jpeg.jpg){fig-alt="Mozilla" width=65px}](https://foundation.mozilla.org/en/blog/mozilla-announces-15-new-responsible-computing-challenge-awardees-in-the-us/)and partners</p>
    center: 
      <p style="color:white">Made with [![](https://raw.githubusercontent.com/github/explore/80f119e965a9a3df7b74c3f7b63a502e3d0ded36/topics/quarto/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)</p>
    
      


format:
  html:
    theme:
        light: [lux, theme.scss]
    css: styles.css
    code-copy: true
    code-overflow: wrap
    include-in-header: 
      - custom-footnotes.js
      - tabs-tocs.js
      - fontawesome.js
    include-after-body:
      - tabs-to-urls.js
      
    
    #  - dynamic-toc.js



