project:
  type: website
  output-dir: ../docs

render:
  - team:
      output-dir: ../docs/team

website:
  title: "Responsible Datasets in Context"
  favicon: images/responsible-logo-white.png
  google-analytics: G-N0Y0SC740G
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
      showHighlights: whenSidebarOpen
  navbar:
    logo: images/responsible-logo-white.png
    right:
      - datasets.qmd
      - text: "About"
        menu: 
        - text: "Team"
          href: team.qmd
        - text: "Mission"
          href: mission.qmd
        - text: "Get Involved"
          href: get-involved.qmd
      - icon: github
        href: https://github.com/melaniewalsh/responsible-datasets-in-context

  page-footer:
    background: "#000000"
    right: <p style="color:white">Copyright &copy; 2024</p>
    left:   <p style="color:white">Supported by[![](https://assets.mofoprod.net/network/images/mo-fo_logo-w.2e16d0ba.fill-890x890-c100.format-jpeg.jpg){fig-alt="Mozilla" width=65px}](https://foundation.mozilla.org/en/blog/mozilla-announces-15-new-responsible-computing-challenge-awardees-in-the-us/)</p>
    center: 
      <p style="color:white">Made with [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)</p>
    
      


format:
  html:
    theme: lux
    css: styles.css
    include-after-body:
      - tabs-to-urls.js
    #  - dynamic-toc.js



