project:
  type: website

website:
  title: "Responsible Datasets in Context"
  navbar:
    right:
      - datasets.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: lux
    css: styles.css



